const words = {
    candidate: '①후보자 ②지원자',
    clients: '고객',
    colleague: '동료',
    department: '①부 ②부서',
    deserves: '①받을 만하다 ②가치가 있다',
    employee: '직원',
    promote: '①홍보하다 ②승진시키다',
    regret: '①후회하다 ②유감',
    absence: '①결석 ②부재',
    afford: '①여유가 있다 ②할 수 있다',
    aware: '①알고 있는 ②인식하는',
    carelessness: '①부주의 ②경솔',
    disappointing: '①실망시키다 ②낙담시키다',
    duties: '①의무 ②임무',
    fulfill: '①이루다 ②이행하다',
    hence: '①그러므로 ②앞으로',
    irresponsible: '①무책임한 ②책임감이 없는',
    unfortunate: '①불행한 ②유감스러운',
    applications: '①적용 ②응용',
    chemistry: '①화학 ②궁합',
    coursework: '①학습 과제 ②교과 학습',
    electrical: '①전기의 ②전자의',
    fascinated: '매료된',
    flexible: '①유연한 ②신축성 있는',
    graphene: '①서기소 ②영어 알파벳의 각 자모 등',
    honored: '①명예로운 ②영광으로 생각하여',
    independent: '①독립한 ②무소속의',
    introductory: '①소개의 ②서두의',
    lab: '①연구실 ②실험실',
    nanotechnology: '①나노 기술 ②나노테크놀로지',
    term: '①용어 ②기간',
    transparent: '①투명한 ②속보이는',
    undergraduate: '①대학의 ②학부의',
    utilized: '①이용하다 ②활용하다',
    application: '①적용 ②응용',
    applied: '①적용된 ②응용의',
    approval: '①승인 ②허가',
    approved: '①승인된 ②통과된',
    deepest: '①깊은 ②긴',
    gratitude: '①감사 ②고마움',
    inform: '알리다',
    insurance: '①보험 ②보험금',
    patience: '①인내 ②참을성',
    policy: '①정책 ②제도',
    provider: '①제공자 ②사업자',
    reference: '①참고 ②기준',
    blizzard: '①블리자드 ②눈보라',
    crouch: '①숙이다 ②구부리다',
    foothills: '히말라야 산맥의 구릉들',
    hillside: '①언덕의 비탈 ②산허리',
    sagebrush: '산쑥',
    slope: '①경사 ②스키장',
    snowy: '①눈 오는 ②눈 덮인',
    steep: '①가파른 ②급격한',
    timbered: '목재',
    upright: '①똑바로 ②직립한',
    vegetated: '①식물로 덮힌 ②식물을 심은',
    devastating: '①큰 타격을 받은 ②황폐한',
    editing: '①편집하다 ②교정하다',
    forehead: '이마',
    intention: '①의도 ②의사',
    promising: '①유망한 ②촉망되는',
    quizzically: '묻는 듯이',
    setback: '①좌절 ②실패',
    shattered: '①산산이 부서진 ②손상된',
    triumphed: '①승리 ②승리감',
    attendants: '①승무원 ②종업원',
    beeswax: '①밀랍 ②일',
    circumstances: '①상황 ②환경',
    collar: '①칼라 ②목걸이',
    delight: '①기쁘게 하다 ②기쁨',
    elegant: '①우아한 ②훌륭한',
    garment: '①의류 ②옷',
    inherit: '①물려받다 ②유전되다',
    sensation: '①감각 ②센세이션',
    smelt: '①용해하다 ②냄새가 느껴졌다',
    softest: '①조용히 ②쉿',
    thrilling: '①스릴 ②흥분',
    unbrushed: '솔질을 하지 않은',
    vastly: '①광대하게 ②막대하게',
    adjust: '①조정되다 ②적응하다',
    boundaries: '①경계를 나타내는 것 ②경계',
    demonstrated: '①논증하다 ②명시하다',
    minimized: '①ㅇㅇ의 양을 최소 한도로 하다 ②최소 한도로 평가하다',
    perspective: '①관점 ②시각',
    spiraled: '①나사선 코스를 잡게 하다 ②나선꼴로 움직이다',
    supportive: '①부양하는 ②지지하는',
    verbalize: '언어로 나타내다',
    accomplishments: '①성취 ②업적',
    legendary: '①전설적인 ②유명한',
    letting: '하게하다',
    scorebook: '①득점 기입장 ②득점 기록부',
    spectacular: '①장관의 ②화려한',
    admire: '①존경하다 ②감탄하다',
    cattle: '소',
    charm: '①매력 ②매혹하다',
    deeds: '①행위 ②행동',
    emotional: '감정적인',
    eventually: '①결국 ②마침내',
    heroic: '①영웅의 ②숭고한',
    inspire: '①영감을 주다 ②고무하다',
    intellect: '①지성 ②지식인',
    irrational: '①비이성적인 ②비합리적인',
    lonesome: '①외로운 ②인적이 드문',
    lovers: '①애인 ②사랑하는 남녀',
    qualities: '①특성 ②성질',
    rangers: '①배회자 ②삼림 경비관',
    rational: '①합리적인 ②이성적인',
    rugged: '①험악한 ②튼튼한',
    sabotage: '①방해 ②파괴',
    sacrifice: '①희생 ②제물',
    surviving: '살아남아 있는',
    anthropologist: '인류학자',
    cosmos: '①우주 ②코스모스',
    distinguished: '①구별하다 ②구분하다',
    theorize: '①이론을 세우다 ②가설을 세우다',
    unfinished: '①미완성의 ②마무리하지 않은',
    advertised: '①광고하다 ②홍보하다',
    avail: '①소용되다 ②쓸모있다',
    bounty: '①박애 ②현상금',
    distinctly: '①분명히 ②뚜렷하게',
    dozens: '①12개 ②수십',
    fortunate: '①운 좋은 ②다행인',
    indebted: '①부채가 있는 ②은혜를 입은',
    laces: '①레이스 ②끈',
    mindlessly: '①조심성 없게 ②부주의하게',
    scuffed: '문질러서 닳은',
    shoeshine: '①구두닦기 ②닦은 구두의 표면',
    advent: '①출현 ②도래',
    aircraft: '①항공기 ②비행기',
    airline: '①항공사 ②비행기',
    cockpit: '①조종석 ②운전석',
    conducts: '①실시하다 ②수행하다',
    delicate: '①섬세한 ②민감한',
    deplanes: '①비행기에서 내리다 ②비행기에서 내리게 하다',
    destinations: '①목적지 ②관광지',
    distinctive: '①독특한 ②특유의',
    germicides: '①살균제 ②살균력 있는',
    insiders: '①관계자 ②내부자',
    inspection: '①검사 ②감사',
    knits: '①뜨개질을 하다 ②니트',
    necessity: '①필요성 ②필수품',
    outsiders: '국외자를 믿지 않다',
    physicians: '영국 의사회',
    procedure: '①절차 ②과정',
    prolonged: '①장기화하다 ②연장하다',
    rites: '의식',
    scrub: '①스크럽 ②문지르다',
    superficial: '①피상적인 ②겉으로 드러나는',
    surgical: '①외과의 ②수술의',
    symbolically: '①상징적으로 ②기호로',
    takeoff: '①이륙하다 ②벗기다',
    undeniable: '①더할 나위 없는 ②부정하기 어려운',
    attitude: '①태도 ②자세',
    besetting: '①끊임없이 따라다니는 ②쉴 새 없이 엄습하는',
    contaminates: '①더럽히다 ②못되게 하다',
    criticism: '①비판 ②비난',
    criticizing: '①비평하다 ②흠을 찾다',
    disapproval: '①반대 ②비난',
    discourages: '①희망을 잃게 하다 ②그만두게 하다',
    dissatisfaction: '①불만 ②불평',
    dogged: '①완고한 ②쉽사리 굽히지 않는',
    excessive: '①과도한 ②지나친',
    misguided: '①잘못 인도된 ②잘못 인식한',
    motivation: '①동기 부여 ②욕구',
    offensive: '①공격 ②모욕적인',
    paternal: '①아버지 같은 ②아버지다운',
    provoking: '①부아가 나는 ②성가신',
    resentment: '①분노 ②적의',
    behaving: '①행동하다 ②예의 바르게 행동하다',
    coated: '①코트 ②칠하다',
    function: '①기능 ②역할',
    predictable: '①예언할 수 있는 ②새로운 게 없는',
    sort: '①분류하다 ②정렬하다',
    appreciation: '①이해 ②감사',
    centered: '중심의',
    civic: '①시민의 ②민간',
    context: '①문맥 ②상황',
    convenience: '①편의 ②편리',
    deprives: '①박탈하다 ②빼앗다',
    individualism: '개인주의',
    inherent: '①내재된 ②고유의',
    interact: '①작용하다 ②교류하다',
    involvement: '①관련 ②개입',
    lack: '①부족 ②ㅇㅇ이 없다',
    leadership: '①리더십 ②지도력',
    mutes: '①무언의 ②약음기',
    participation: '①참여 ②참가',
    perception: '①인식 ②지각',
    relativity: '①상대성 ②상대성 원리',
    rotates: '①회전하다 ②순환하다',
    undue: '①과도한 ②심한',
    weakness: '①약함 ②약점',
    acquire: '①얻다 ②습득하다',
    conscious: '①의식한 ②친화적',
    fuzzy: '①보풀로 덮인 ②보풀 모양의',
    illogical: '①비논리적인 ②조리가 닿지 않는',
    prevalence: '①보급 ②유행',
    rigid: '①경직된 ②엄격한',
    techniques: '①기법 ②기술',
    assume: '①가정하다 ②생각하다',
    conducted: '①실시하다 ②수행하다',
    ensure: '①ㅇㅇ하기 위해 ②보장하다',
    phrase: '①말 ②구절',
    refers: '언급하다',
    reliability: '①신뢰성 ②신뢰도',
    reliably: '①확실하게 ②의지할 수 있게',
    replicated: '①반복되는 ②많은',
    significance: '중요성',
    significant: '①중요한 ②상당한',
    statistical: '①통계의 ②통계상의',
    term: '①용어 ②기간',
    unfortunate: '①불행한 ②유감스러운',
    vocabulary: '①어휘 ②단어',
    exist: '①존재하다 ②있다',
    function: '①기능 ②역할',
    groves: '작은 숲',
    intend: '①의도하다 ②계획하다',
    occupy: '①점령하다 ②차지하다',
    perceive: '①인지하다 ②인식하다',
    sacred: '①신성한 ②성스러운',
    sanity: '①온전한 정신 ②판단의 건전함',
    semiprivate: '①소수용인 ②반사적인',
    survival: '①생존 ②살아남기',
    wilderness: '①황야 ②자연',
    beneficial: '①이로운 ②유익한',
    encounters: '①만나다 ②마주치다',
    examine: '①조사하다 ②검토하다',
    prescribe: '①처방하다 ②규정하다',
    promotion: '①홍보 ②승진',
    realities: '①현실 ②실물과 꼭 같음',
    remedies: '①의약품 ②교정 수단',
    selected: '①선택된 ②선발된',
    absorbing: '①흡수하다 ②열중하다',
    acoustical: '①청각의 ②소리의',
    aesthetically: '①미적으로 ②심미적으로',
    avoided: '①피하다 ②무효로 하다',
    beneath: '①아래에 ②밑에',
    conditioners: '조절 장치',
    considerations: '①고려 ②배려',
    drafty: '①외풍이 있는 ②통풍이 잘되는',
    draperies: '마루까지 닿는 휘장',
    ducts: '①도관으로 보내다 ②도관',
    instrument: '①악기 ②도구',
    satisfactory: '만족스러운',
    sprinkler: '살수기',
    aggressiveness: '①공격성 ②적극성',
    approach: '①접근하다 ②접근법',
    assertiveness: '단호한 태도',
    associated: '①연관된 ②관계가 있는',
    circumstances: '①상황 ②환경',
    confront: '①직면하다 ②맞서다',
    fearful: '①두려워하는 ②무서운',
    leadership: '①리더십 ②지도력',
    optimistic: '①낙관적인 ②긍정적인',
    outcomes: '①결과 ②성과',
    perceptions: '①인식 ②지각',
    persistence: '①고집 ②지속',
    pessimism: '①비관론 ②비관주의',
    powerless: '①효과 없는 ②무효의',
    requirement: '필요조건',
    retreat: '①후퇴 ②물러서다',
    submissive: '①순종하는 ②복종하는',
    theorists: '이론가',
    attaining: '①달성하다 ②이루다',
    distorted: '①왜곡하다 ②뒤틀다',
    lottery: '①복권 ②추첨',
    righteousness: '①정직 ②고결',
    scarce: '①부족한 ②희귀한',
    theology: '①신학 ②신학 이론',
    advantage: '①이점 ②우위',
    apocryphal: '①저작자가 미심쩍은 ②가짜의',
    assured: '①보증된 ②자신이 있는',
    calculations: '①계산 ②측정',
    conducted: '①실시하다 ②수행하다',
    conflict: '①갈등 ②분쟁',
    consequences: '①결과 ②대가',
    derived: '①유래된 ②유도',
    digesting: '①소화하다 ②먹다',
    economic: '①경제의 ②경기의',
    intellectuals: '①지적인 ②지성을 지닌',
    irrational: '①비이성적인 ②비합리적인',
    pathology: '①병상 ②병리학',
    politics: '①정치 ②정계',
    profit: '①이익 ②수익',
    rational: '①합리적인 ②이성적인',
    accumulated: '①쌓아 올리다 ②쌓이다',
    appliances: '①가전제품 ②기기',
    assets: '①자산 ②재산',
    contribute: '①기여하다 ②공헌하다',
    drastically: '①과감하게 ②철저히',
    economic: '①경제의 ②경기의',
    elders: '①노인 ②어른',
    entrepreneurial: '기업가의',
    imperative: '①필수의 ②반드시 ㅇㅇ해야 하는',
    investment: '①투자 ②출자',
    percentage: '①포인트 ②비율',
    purchases: '①구매하다 ②구입하다',
    retire: '①은퇴하다 ②퇴직하다',
    retiring: '①은퇴의 ②퇴직의',
    workforce: '①전 종업원 ②노동 인구',
    arrival: '①도착 ②등장',
    attempt: '①시도하다 ②노력',
    caretaker: '①관리인 ②돌보는 사람',
    concern: '①우려 ②관한',
    desperate: '①필사적인 ②절실한',
    extinctions: '①소멸 ②멸종',
    flightless: '날지 못하는',
    impact: '①영향 ②충격',
    individuals: '개인들',
    invaded: '①침입하다 ②쳐들어가다',
    isolating: '①분리하다 ②고립시키다',
    keen: '①예민한 ②예리한',
    naturalist: '①박물학자 ②동물학자',
    occupied: '①차지하다 ②끌다',
    predation: '①약탈 ②포식',
    predator: '①포식자 ②약탈자',
    remote: '①원격의 ②외딴',
    resolution: '①결의 ②해상도',
    stoats: ' 족제비',
    technique: '①기법 ②기술',
    translocated: '①ㅇㅇ의 장소를 옮기다 ②전류시키다',
    attitudes: '①태도 ②자세',
    authoritatively: '①위엄을 가지고 ②명령조로',
    constructive: '건설적인',
    context: '①문맥 ②상황',
    desires: '①욕망을 가지다 ②바라다',
    eagerness: '①열의 ②열망',
    enlist: '①입대 ②요청',
    exemplify: '①보여주다 ②예이다',
    foundation: '①재단 ②기반',
    fulfilling: '①이루다 ②이행하다',
    identities: '①동일함 ②본인임',
    individual: '개인의',
    purposeful: '①목적 있는 ②의도를 가진',
    refusal: '①거부 ②거절',
    signify: '①의미하다 ②나타내다',
    supportive: '①부양하는 ②지지하는',
    tolerant: '①내성이 있는 ②관대한',
    urges: '①충동 ②열망',
    validates: '정당성을 입증하다',
    victimized: '①손해를 주다 ②제물로서 죽이다',
    attentive: '①주의 깊은 ②세심한',
    compromised: '①타협하다 ②절충하다',
    considerations: '①고려 ②배려',
    contribute: '①기여하다 ②공헌하다',
    household: '①가구 ②가정의',
    involved: '①관련된 ②관여하는',
    joint: '①공동의 ②관절',
    maintain: '①유지하다 ②계속하다',
    managing: '①관리 ②간부',
    manger: '①여물통 ②구유',
    negotiate: '①협상하다 ②협의하다',
    preferences: '①선호 ②좋아하기',
    academy: '①아카데미 ②학술원',
    appreciation: '①이해 ②감사',
    diploma: '①졸업장 ②학위',
    homeland: '①조국 ②고향',
    illustrated: '①설명하다 ②묘사하다',
    illustrating: '①설명하다 ②묘사하다',
    increase: '①증가하다 ②늘리다',
    pacifist: '①평화주의자 ②반전론자',
    stance: '①입장 ②자세',
    subsequently: '①뒤에 ②다음에',
    trade: '①무역 ②거래',
    attempting: '①시도하다 ②노력',
    belly: '①배 ②부풀다',
    blending: '①혼합 ②혼합물',
    breed: '①품종 ②육성',
    cottontail: '솜꼬리토끼',
    derived: '①유래된 ②유도',
    dig: '①파다 ②발굴하다',
    disused: '①사용되지 않는 ②폐지된',
    dug: '①dig의 과거 과거 분사형 ②젖꼭지',
    establish: '①설립하다 ②세우다',
    hierarchies: '①계층제 ②성직 위계제',
    mates: '①짝 ②배우자',
    outrun: '①ㅇㅇ보다 멀리 달리다 ②앞지르다',
    predators: '①포식자 ②약탈자',
    pursuers: '추적자들',
    restricted: '①제한된 ②한정된',
    rounded: '①둥글게 된 ②완성된',
    shallow: '①얕은 ②얄팍한',
    surroundings: '①주위의 ②주변의',
    underside: '①이면 ②밑바닥',
    zigzag: '①지그재그로 하다 ②지그재그로',
    acre: '①에이커 ②많은',
    aesthetics: '①미학 ②미적 감각',
    appreciation: '①이해 ②감사',
    bigelow: '아카시아나무',
    correlation: '①상호 관계 ②상관 관계',
    dabbled: '①튀기다 ②첨벙 처넣다',
    encounter: '①만나다 ②마주치다',
    estate: '①재산 ②소유권',
    extensive: '①광범위한 ②대규모의',
    formal: '①공식적인 ②정식의',
    fostered: '①육성하다 ②증진하다',
    interval: '①간격 ②구간',
    profoundly: '①깊은 곳에서 ②절실히',
    resided: '①거주하다 ②존재하다',
    schooled: '①가르치다 ②교육하다',
    summed: '합계하다',
    concentration: '①농축 ②집중',
    distributing: '①분배하는 ②배급하는',
    industry: '①산업 ②업계',
    mechanism: '①메커니즘 ②장치',
    patent: '①특허 ②보호',
    productivity: '①생산성 ②생산력',
    settled: '①안정된 ②정착한',
    tacks: '①대가리가 납작한 못 ②시침질',
    beam: '①빔 ②광선',
    brilliance: '①광휘 ②광채',
    educating: '①교양 있는 ②교육을 받은',
    forgotten: '잊혀진',
    impact: '①영향 ②충격',
    imprisonment: '①투옥 ②감금',
    incandescent: '①백열의 ②고온에 의해 생기는',
    injustice: '①부정 ②부당',
    lightening: '①밝아지다 ②번쩍 빛나다',
    prejudicing: '①편견 ②침해',
    privileged: '①특권의 ②혜택',
    racial: '①인종의 ②민족의',
    relativity: '①상대성 ②상대성 원리',
    spark: '①촉발시키다 ②스파크',
    transform: '①바꾸어 놓다 ②변화시키다',
    absorbed: '①흡수하다 ②열중하다',
    alienation: '①소외 ②양도',
    americanized: '①미국식으로 하다 ②미국화하다',
    appeal: '①호소 ②매력',
    approximately: '①약ㅇㅇ ②ㅇㅇ여',
    commercial: '①상업용의 ②상업적인',
    consequently: '①결과적으로 ②그에 따른',
    declared: '①선언된 ②선포',
    eclectic: '①절충적인 ②다양한',
    freedom: '①자유 ②석방',
    heartfelt: '①진심어린 ②진정어린',
    homegrown: '①자기 집에서 기른 ②당지 산의',
    identity: '①정체성 ②자신',
    industry: '①산업 ②업계',
    instrumental: '①주된 역할을 하는 ②기악',
    minstrel: '①음유 시인 ②시인',
    offshoot: '①분지 ②나뭇가지',
    oral: '①입의 ②구두의',
    sacred: '①신성한 ②성스러운',
    selections: '①선택 ②선발',
    symbolic: '상징적인',
    tunes: '①조율하다 ②맞추다',
    unmistakable: '①명백한 ②틀릴 여지가 없는',
    versions: '①버전 ②판',
    accomplish: '①성취하다 ②이루어 내다',
    busyness: '①분주함 ②다망',
    determines: '①결정하다 ②결심하다',
    equal: '①평등한 ②동등한',
    mindlessly: '①조심성 없게 ②부주의하게',
    prioritize: '①우선시하다 ②우선순위',
    prioritizing: '①우선 순위를 매기다 ②중요한 것부터 들다',
    productivity: '①생산성 ②생산력',
    scroll: '①스크롤 ②두루마리',
    unconscious: '①무의식의 ②의식을 잃은',
    access: '접근',
    brilliant: '①훌륭한 ②뛰어난',
    conceived: '①마음에 품다 ②상상하다',
    employs: '고용하다',
    essence: '①본질 ②정수',
    established: '①설립하다 ②세우다',
    hence: '①그러므로 ②앞으로',
    imitation: '①모방 ②모조품',
    indicate: '①나타내다 ②가리키다',
    ingenium: '①재능 ②재능 있는 사람',
    inspiration: '①영감 ②자극',
    intuition: '①직관적 통찰 ②직감',
    methodically: '①질서 있게 ②조직적으로',
    precepts: '①가르침 ②지시',
    productivity: '①생산성 ②생산력',
    scientifically: '과학적으로',
    significance: '중요성',
    term: '①용어 ②기간',
    traced: '①자취 ②자취',
    attempts: '①시도하다 ②노력',
    claiming: '①주장하다 ②말하다',
    commonplace: '①흔한 ②다반사',
    contestants: '①경쟁자 ②논쟁자',
    diet: '식단',
    factors: '①요소 ②인수',
    fads: '①페이딩 ②쇠퇴',
    impatience: '①성급함 ②안달',
    implies: '①뜻을 함축하다 ②암시하다',
    trim: '①잘라내다 ②다듬다',
    waistline: '①허리의 선 ②허리 둘레',
    accuracy: '①정확도 ②정확',
    anonymously: '①익명으로 ②특색 없이',
    clip: '①동영상 ②클립',
    predict: '①예측하다 ②전망하다',
    psychological: '①심리학의 ②정신의',
    revealed: '①드러내다 ②나타내다',
    alien: '①외계인 ②외국인',
    alternatives: '①양자택일 ②한쪽',
    assigned: '①부여하다 ②할당하다',
    consequences: '①결과 ②대가',
    countless: '①많은 ②셀 수 없는',
    cultivate: '①재배하다 ②양성하다',
    empathize: '①감정 이입을 하다 ②공감하다',
    encounter: '①만나다 ②마주치다',
    engaged: '①통화 중인 ②바쁜',
    enliven: '①활기띠게 하다 ②약동하게 하다',
    envision: '①상상하다 ②마음에 그리다',
    fantasy: '①공상 ②몽상',
    flexibility: '①융통성 ②구부리기 쉬움',
    interacting: '①작용하다 ②교류하다',
    minimally: '최소한으로',
    multiple: '다수의',
    narrative: '①설명적인 ②이야기',
    utilizing: '①이용하다 ②활용하다',
    advertiser: '①광고자 ②광고인',
    afford: '①여유가 있다 ②할 수 있다',
    appliance: '①가전제품 ②기기',
    comparisons: '비교',
    concern: '①우려 ②관한',
    consumer: '①소비자 ②고객',
    copywriter: '①광고 문안가 ②원고를 쓰는 사람',
    crafted: '①공예 ②만들다',
    dishwashing: '①접시 씻기 ②접시 씻는',
    flipping: '①앗',
    granted: '①부여하다 ②주다',
    housekeeping: '①살림 ②안내',
    pang: '①격통 ②양심의 가책',
    persuasion: '①설득 ②신앙',
    purchase: '①구매하다 ②구입하다',
    alternatives: '①양자택일 ②한쪽',
    automatically: '①자동적으로 ②자연히',
    cohesive: '①점착성이 있는 ②응집력이 있는',
    consensus: '①합의 ②의견',
    consideration: '①고려 ②배려',
    contrary: '①반대의 ②정반대의',
    deviate: '①벗어나다 ②빗나가다',
    discord: '①불화 ②불일치',
    effectiveness: '①효과적인 ②유효성',
    enormous: '①엄청난 ②거대한',
    established: '①설립하다 ②세우다',
    exclusion: '①배제 ②제외',
    panels: '①틀 ②천장널',
    politically: '①정치적으로 ②정략적으로',
    psychologist: '①심리학자 ②정신과 의사',
    rejected: '①거절하다 ②버리다',
    relevance: '①관련 ②관련성',
    ridiculed: '①비웃다 ②조롱하다',
    stature: '①신장 ②키',
    urge: '①촉구하다 ②요구하다',
    backdrop: '①배경막 ②배경막을 달다',
    barely: '①거의 ㅇㅇ않다 ②겨우',
    billowing: '①파도치게 하다 ②큰 파도',
    blooded: '①혈액 ②피',
    chirping: '①찍찍 ②찍찍 울다',
    constant: '①일정한 ②지속적인',
    decent: '①제대로 된 ②품위있는',
    frequency: '①주파수 ②빈도',
    grasses: '①풀 ②볏과의 식물',
    grasshoppers: '메뚜기가 뛰다',
    habitat: '①서식지 ②생태',
    herbs: '①풀 ②초본류',
    orchestral: '오케스트라의',
    regulate: '①규제하다 ②조절하다',
    soundscape: '①소리의 퍼짐 ②음향의 세계',
    squeak: '찍찍거리다',
    threshold: '①기준점 ②입구',
    vibrations: '진동을 일으키다',
    attitudes: '①태도 ②자세',
    bonuses: '①ㅇㅇ에게 보너스를 주다 ②특별 수당',
    cadres: '①기간 요원 ②간부단의 일원',
    conformity: '①일치 ②적합',
    corporate: '①기업의 ②회사의',
    corporation: '①기업 ②회사',
    defined: '정의된',
    dictated: '① ②구술하다',
    duties: '①의무 ②임무',
    earnest: '①진지한 ②성실한',
    irresistible: '①저항할 수 없는 ②억누를 수 없는',
    keyed: '①건이 있는 ②조절한',
    promotion: '①홍보 ②승진',
    rebellion: '①반란 ②반항',
    secure: '①확보하다 ②안전한',
    stockholders: '주주명부',
    sweep: '쓸다',
    admit: '①인정하다 ②시인하다',
    attempted: '①시도하다 ②노력',
    forgotten: '잊혀진',
    imitate: '①모방하다 ②흉내내다',
    mathematical: '①수학의 ②수리적인',
    precise: '①정밀한 ②정확한',
    prejudice: '①편견 ②선입관',
    primarily: '①주로 ②우선',
    profound: '①심오한 ②깊은',
    quantification: '①정량화 ②수량화',
    quantified: '①ㅇㅇ의 분량을 정하다 ②양을 명시하다',
    quantify: '①정량화하다 ②양을 재다',
    rationally: '①이성적으로 ②합리적으로',
    techniques: '①기법 ②기술',
    apparent: '①분명한 ②명백한',
    assumptions: '①가정 ②추측',
    bounded: '①경계가 있는 ②구획된',
    commonsense: '①상식 ②흔히 볼 수 있는',
    consists: '①이루어지다 ②구성되다',
    define: '①정의하다 ②말한다',
    disappearance: '①사라짐 ②소멸',
    eliminating: '①제거하다 ②실격시키다',
    evaluated: '①평가하다 ②수치를 구하다',
    exotic: '①이국적인 ②이국풍의',
    extent: '①정도 ②범위',
    fundamental: '①기본적인 ②근본적인',
    heterodoxy: '①이단 ②비정통',
    illustration: '삽화',
    minded: '①ㅇㅇ한 마음을 가진 ②ㅇㅇ에 흥미가 있는',
    morality: '도덕성',
    observation: '①관찰 ②관측',
    orthodoxy: '①정통파적 신념 ②정교적 신앙',
    perceptible: '①지각할 수 있는 ②지각할 수 있을 만큼의',
    seek: '①추구하다 ②찾다',
    span: '①걸치다 ②기간',
    stock: '①주식 ②증권',
    timber: '목재',
    universal: '①보편적인 ②전 세계의',
    whooping: '①환성을 지르며 말하다 ②와',
    accurately: '①정확하게 ②그대로',
    attain: '①달성하다 ②이루다',
    basically: '기본적으로',
    conception: '①개념 ②계획',
    differ: '①다르다 ②차이',
    hardwired: '배선에 의한',
    individuals: '개인들',
    inherit: '①물려받다 ②유전되다',
    innate: '①타고난 ②선천적인',
    limited: '①한정된 ②제한을 받은',
    minimally: '최소한으로',
    musicality: '①음악성 ②음악에의 재능',
    orators: '①연설자 ②대표 연설자',
    participation: '①참여 ②참가',
    societies: '사회',
    allies: '①ally의 복수형 ②연합국',
    arguably: '①아마 틀림없이 ②논증할 수 있는 일이지만',
    crises: '①위기 ②위기 일발의 장면',
    determined: '①결정된 ②결심한',
    disturbing: '방해하다',
    essay: '①수필 ②논문',
    established: '①설립하다 ②세우다',
    examined: '①검사하다 ②시험하다',
    intriguingly: '흥미롭게도',
    outcome: '①결과 ②성과',
    resolved: '①결심한 ②결심이 굳은',
    tensions: '①팽팽하게 치기 ②긴장',
    trigger: '①촉발 ②유발하다',
    afterlife: '①내세 ②사후의 생명',
    burial: '①매장 ②묘소',
    deceased: '①사망한 ②죽은',
    dehydrate: '①탈수시키다 ②건조시키다',
    dug: '①dig의 과거 과거 분사형 ②젖꼭지',
    elaborate: '정교하게하다',
    era: '①시대 ②시절',
    foetal: '①태아의 ②태아의 상태의',
    fundamental: '①기본적인 ②근본적인',
    gradual: '①점진적인 ②조금씩',
    lifelike: '①실물과 똑같은 ②살아 있는 듯한',
    mummification: '미라화',
    practised: '연습하다',
    preferences: '①선호 ②좋아하기',
    preservation: '①보존 ②보전',
    readiness: '①준비 ②신속',
    rebirth: '①갱생 ②부활',
    retained: '①유지하다 ②보유하다',
    sophisticated: '①정교한 ②복잡한',
    underworld: '①하층 사회 ②악의 세계',
    businessman: '①사업가 ②기업인',
    deprived: '①박탈하다 ②빼앗다',
    depriving: '①박탈하다 ②빼앗다',
    enmity: '①적의 ②증오',
    obsessed: '①빠져있는 ②집착',
    steer: '①조종하다 ②돌리다',
    appreciatively: '①고마워서 ②감탄하여',
    artful: '①교활한 ②교묘한',
    blend: '①혼합 ②혼합물',
    masterpiece: '①걸작 ②명작',
    noticeable: '①눈에 띄는 ②주목할 만한',
    recognised: '인정하다',
    rightful: '①합법적인 ②적법의',
    sector: '①부문 ②분야',
    simplicity: '①단순 ②간단',
    suspected: '의심이 가는',
    vanished: '①사라지다 ②자취를 감추다',
    buggy: '①유모차 ②사륜차',
    instincts: '①본능 ②타고난 재능',
    miser: '①구두쇠 ②수전노',
    motored: '①모터 ②자동차',
    occasion: '①경우 ②때',
    trotted: '①속보로 달리다 ②빠른 걸음으로 가다',
    affairs: '①문제 ②일',
    backed: '①등가 달린 ②뒷받침이 있는',
    claim: '①주장하다 ②말하다',
    domestic: '①국내의 ②내수',
    exert: '①영향을 미치다 ②행사하다',
    insightful: '①통찰력 있는 ②영감있는',
    marked: '①표시하다 ②두드러진',
    monarch: '①군주 ②거물',
    mustn: 'must not의 단축형',
    policy: '①정책 ②제도',
    resign: '①사임 ②사퇴',
    threatened: '①위협당한 ②협박당한',
    vomiting: '①구토 ②토하기',
    accessibility: '접근하기 쉬움',
    accessible: '접근할 수 있는',
    activated: '①활성화된 ②술취한',
    applied: '①적용된 ②응용의',
    charisma: '①비범한 통솔력 ②남을 끌어당기는 강한 개성',
    chronically: '만성적으로',
    context: '①문맥 ②상황',
    determined: '①결정된 ②결심한',
    differ: '①다르다 ②차이',
    encountered: '①만나다 ②마주치다',
    entertainment: '①오락 ②연예',
    evaluating: '①평가하다 ②수치를 구하다',
    evaluator: '①평가자 ②평가하는 사람',
    heightened: '①높게 하다 ②증가시키다',
    illustrate: '①설명하다 ②묘사하다',
    involved: '①관련된 ②관여하는',
    likelihood: '①가능성 ②기회',
    persuasive: '①설득력 있는 ②설득적인',
    schema: '①개요 ②선험적 도식',
    stimulus: '①자극 ②부양책',
    additionally: '①게다가 ②또한',
    attend: '①참석하다 ②다니다',
    convincingly: '납득이 가도록',
    elaborated: '정교하게하다',
    existence: '①존재 ②현존',
    gregarious: '①사교적인 ②무리의',
    instinct: '①본능 ②직감',
    isolated: '①고립된 ②절연된',
    labeling: '이름 붙이기',
    motives: '①동기 ②의도',
    proportion: '①비율 ②비례',
    tautology: '①동의어 반복 ②같은 말의 반복',
    aroused: '흥분한',
    attempting: '①시도하다 ②노력',
    calmness: '①고요 ②평온',
    colleague: '동료',
    convinced: '①확신하는 ②설득했다',
    distractions: '①주의 산만 ②혼란',
    languid: '①나른한 ②노곤한',
    napping: '①잠시 졸다 ②선잠',
    orchestrated: '①편곡된 ②편성된',
    prolifically: '①다산하여 ②다작하여',
    punctuated: '①강조하다 ②구두점을 찍다',
    sipping: '홀짝홀짝 마시다',
    slots: '①시간대 ②자리',
    stillness: '①부동 ②정적',
    unstructured: '체계적으로 조직되어 있지 않은',
    authoritatively: '①위엄을 가지고 ②명령조로',
    charge: '①혐의 ②충전',
    collectively: '①전체적으로 ②일괄하여',
    consciousness: '①의식 ②인식',
    entail: '①수반하다 ②필요로 하다',
    impose: '①부과하다 ②제한하다',
    improvements: '①개선 ②향상',
    individuals: '개인들',
    inhabitants: '①주민 ②사람',
    macrocosmic: '①대우주의 ②전체계의',
    meaningful: '①의미 있는 ②의미심장한',
    microcosmic: '①소우주의 ②소세계의',
    resolve: '①해결하다 ②결심하다',
    anonymous: '①익명의 ②이름을 밝히지 않은',
    collective: '①집단적인 ②공동의',
    combining: '①결합시키다 ②합치다',
    comprises: '①ㅇㅇ로 이뤄지다 ②구성하다',
    conform: '①순응하다 ②따르다',
    consensus: '①합의 ②의견',
    consulted: '①조언을 청하다 ②참고하다',
    feedback: '①피드백 ②반응',
    gauge: '①측정하다 ②척도',
    modify: '①변경하다 ②변형하다',
    mythology: '①신화 ②신화학',
    project: '계획',
    proven: '①증명된 ②입증된',
    refers: '언급하다',
    respondent: '①응하는 ②응답자',
    significant: '①중요한 ②상당한',
    structured: '①구조화 된 ②구조가 있는',
    summarized: '①요약하다 ②요점을 이루다',
    technique: '①기법 ②기술',
    term: '①용어 ②기간',
    waging: '①임금 ②보답',
    admitted: '①인정된 ②시인',
    architecture: '①건축 ②설계',
    bias: '①편견 ②치우침',
    generation: '①세대 ②시대',
    hence: '①그러므로 ②앞으로',
    innate: '①타고난 ②선천적인',
    perspective: '①관점 ②시각',
    racial: '①인종의 ②민족의',
    sociological: '①사회 조직의 ②사회의',
    sociology: '①사회과학 ②사회학',
    structure: '①구조 ②구성하다',
    undergraduates: '①대학의 ②학부의',
    elaboration: '①정교 ②상세화',
    fantasy: '①공상 ②몽상',
    formation: '①형성 ②대형',
    impersonal: '①비인간적인 ②냉담한',
    manifestations: '①명시 ②시위',
    mythological: '①신화학의 ②신화의',
    mythology: '①신화 ②신화학',
    origin: '①기원 ②원산',
    personifications: '①의인화 ②화신',
    personifying: '①의인화하다 ②인간화하다',
    phenomena: '현상들',
    predominance: '①우월 ②우위',
    respective: '①각각의 ②각자의',
    surroundings: '①주위의 ②주변의',
    thunderstorms: '심한 뇌우',
    veneration: '①존경 ②숭배',
    advertisers: '①광고자 ②광고인',
    airwaves: '방송',
    alternative: '①대안 ②대체',
    broader: '①폭이 넓은 ②광대한',
    civic: '①시민의 ②민간',
    concentration: '①농축 ②집중',
    conglomerates: '①집합 ②복합 기업',
    corporate: '①기업의 ②회사의',
    corporations: '①기업 ②회사',
    democracy: '①민주주의 ②민주적',
    diverse: '①다양한 ②여러 가지의',
    exist: '①존재하다 ②있다',
    functioning: '①기능 ②의식',
    independent: '①독립한 ②무소속의',
    integral: '①완전한 ②필수의',
    legitimately: '합법적으로',
    maintain: '①유지하다 ②계속하다',
    networks: '①네트워크 ②망',
    noncommercial: '①비상업적인 ②상업적으로 중요하지 않은',
    participation: '①참여 ②참가',
    political: '①정치의 ②정당의',
    politicians: '정치가',
    reclaim: '①교정하다 ②개선하다',
    transnational: '①다국적 기업의 ②다국적의',
    agoraphobia: '①광장 공포 ②광장 공포증',
    conducted: '①실시하다 ②수행하다',
    confined: '①국한 ②제한된',
    considerable: '①상당한 ②꽤',
    curl: '곱슬곱슬하다',
    deprived: '①박탈하다 ②빼앗다',
    determine: '①결정하다 ②밝히다',
    disposed: '①경향이 있는 ②마음이 나는',
    rehabilitate: '①명예를 회복시키다 ②사회로 복귀시키다',
    terrified: '①무서워하는 ②오싹한',
    cognitive: '①인식의 ②인지의',
    context: '①문맥 ②상황',
    cyclical: '순환하는',
    established: '①설립하다 ②세우다',
    forgotten: '잊혀진',
    fundamentally: '①근본적으로 ②기본적으로',
    indefinitely: '①무기한으로 ②무한정',
    inherently: '①본질적으로 ②생득적으로',
    renewed: '①새롭게 한 ②회복된',
    spans: '①걸치다 ②기간',
    technological: '기술적인',
    timeless: '①시간을 초월한 ②무한한',
    underlying: '①기초를 이루는 ②근원적인',
    agnostic: '①관대한 ②열려있는',
    appliance: '①가전제품 ②기기',
    deems: '①간주하다 ②생각하다',
    demand: '①요구하다 ②수요',
    fabrication: '①제작 ②제조',
    facility: '①시설 ②설비',
    fundamentally: '①근본적으로 ②기본적으로',
    independent: '①독립한 ②무소속의',
    manufacturing: '①제조 ②생산',
    occurred: '발생하다',
    offshore: '①앞바다의 ②앞바다에서',
    precisely: '①정확히 ②정밀하게',
    production: '①생산 ②제작',
    reshored: '①복원하다 ②회복하다',
    supplier: '①공급하는 사람 ②원료 공급국',
    term: '①용어 ②기간',
    approve: '①승인하다 ②허가하다',
    assigned: '①부여하다 ②할당하다',
    colleagues: '동료',
    demand: '①요구하다 ②수요',
    depend: '의존하다',
    essay: '①수필 ②논문',
    esteem: '①존중하다 ②평가하다',
    excluded: '①제외하다 ②배제하다',
    extent: '①정도 ②범위',
    indicate: '①나타내다 ②가리키다',
    involved: '①관련된 ②관여하는',
    momentary: '순간의',
    participant: '①참가자 ②참여자',
    preferences: '①선호 ②좋아하기',
    colleagues: '동료',
    communicator: '①전달자 ②발신기',
    impact: '①영향 ②충격',
    inquiry: '①조사 ②문의',
    intensely: '①격렬히 ②강렬하게',
    isolated: '①고립된 ②절연된',
    lab: '①연구실 ②실험실',
    loners: '①남과 사귀지 않는 사람 ②혼자 행동하는 사람',
    portray: '①묘사하다 ②연기하다',
    seminars: '①세미나 ②연구집회',
    undergraduate: '①대학의 ②학부의',
    vetted: '①진료하다 ②심사하다',
    adolescence: '①청소년기 ②사춘기',
    advancing: '①전진하는 ②발달의',
    antibodies: '①항체 ②항독소',
    attack: '①공격하다 ②발작',
    autoimmune: '자기 면역의',
    decline: '①감소하다 ②거절하다',
    defective: '①결함있는 ②불량품',
    defense: '①국방 ②방어',
    eventually: '①결국 ②마침내',
    function: '①기능 ②역할',
    hostile: '①적대적인 ②호전적인',
    immune: '①면역의 ②면제된',
    incidence: '①발생률 ②발생',
    integrity: '①진실성 ②도덕성',
    invaders: '①침입자 ②침략국',
    tissues: '①조직 ②화장지',
    vulnerability: '①약점이 있음 ②공격당하기 쉬움',
    weakening: '①약화시키다 ②약해지다',
    approximation: '①접근 ②근사',
    concerning: '관한',
    emotional: '감정적인',
    intention: '①의도 ②의사',
    involving: '관련하는',
    isolated: '①고립된 ②절연된',
    patron: '①후원자 ②고객',
    perceptions: '①인식 ②지각',
    acceptable: '받아들일만한',
    access: '접근',
    consumption: '①소비 ②소비량',
    costly: '①값이 비싼 ②사치스러운',
    dined: '①ㅇㅇ과 정찬을 들다 ②ㅇㅇ에게 정찬을 대접하다',
    granted: '①부여하다 ②주다',
    hierarchy: '①계급 제도 ②계층제',
    inferiors: '①열등한 ②질이 떨어지는',
    medieval: '중세의',
    nobility: '①귀족 ②고귀함',
    positioned: '①두다 ②ㅇㅇ의 위치를 정하다',
    privileges: '①특권을 주다 ②면제하다',
    referring: '언급하다',
    reflected: '①반사하다 ②보여주다',
    rigid: '①경직된 ②엄격한',
    royalty: '①로열티 ②왕정',
    atoms: '①원자 ②원자력',
    copper: '①구리 ②동전',
    hunk: '①큰 덩어리 ②자기 진지',
    impact: '①영향 ②충격',
    infinite: '①무한한 ②끝없는',
    molecules: '분자',
    apparently: '①분명히 ②명백히',
    constraint: '①제약 ②조건',
    controlled: '①제어 ②통제당한',
    decline: '①감소하다 ②거절하다',
    dyslexia: '①난독증 ②독서 장애',
    enable: '가능하게하다',
    healed: '①치유되다 ②치료하다',
    impairment: '①해침 ②손상',
    induced: '①유발하다 ②유도하다',
    limb: '①팔다리 ②의족',
    plasticity: '①가소성 ②유연성',
    restrained: '①삼가는 ②자제된',
    technique: '①기법 ②기술',
    aesthetic: '미학의',
    apparent: '①분명한 ②명백한',
    aspect: '①양상 ②측면',
    conversion: '①전환 ②변화',
    dense: '①밀집한 ②고밀도의',
    emphasize: '①강조하다 ②힘주어 말하다',
    impact: '①영향 ②충격',
    inductive: '①유도의 ②귀납의',
    ratios: '비율',
    receiver: '①수신기 ②수신자',
    sequencing: '①배열 ②순서',
    squeezing: '수분을 짜다',
    attractive: '①매력적인 ②매혹적인',
    carriageway: '①차도 ②자동차 도로',
    centre: '중심',
    crossings: '횡단보도',
    discourage: '①낙담시키다 ②단념시키다',
    edges: '①가장자리 ②끝',
    extend: '①확장하다 ②연장하다',
    fatal: '①치명적인 ②죽음에 이르는',
    interchanges: '①주고받다 ②교환하다',
    junctions: '①접합 ②연락점',
    landscaping: '조경',
    permitted: '①허용하다 ②인가',
    proximity: '①근접 ②가까움',
    resultant: '결과로서 생기는',
    revegetation: '식물을 다시 자라게 함',
    roadside: '①길가 ②노변',
    roundabouts: '①멀리 도는 ②자락을 평평하게 자른',
    selected: '①선택된 ②선발된',
    techniques: '①기법 ②기술',
    vegetative: '①식물의 ②식물 인간의',
    verges: '①가장자리 ②경계',
    visibility: '①눈에 보임 ②가시성',
    widened: '①넓히다 ②넓어지다',
    wildlife: '야생의',
    accuracy: '①정확도 ②정확',
    adequately: '①적절히 ②충분히',
    astonishing: '①놀라운 ②놀라게 하다',
    cacophony: '①불협화음 ②소음',
    constantly: '①끊임없이 ②계속',
    definable: '①한정할 수 있는 ②설명할 수 있는',
    diverse: '①다양한 ②여러 가지의',
    drowned: '①익사하다 ②물에 빠지다',
    focuses: '①초점에 모이다 ②주의를 집중하다',
    genuine: '①진실된 ②진짜의',
    habitat: '①서식지 ②생태',
    precisely: '①정확히 ②정밀하게',
    rivals: '①경쟁하는 ②경쟁자',
    slot: '①시간대 ②자리',
    solstice: '①동지 ②하지',
    specific: '①특정한 ②구체적인',
    auditory: '①귀의 ②청각의',
    commercial: '①상업용의 ②상업적인',
    compressed: '①압축하다 ②습포',
    compression: '①압축 ②응축',
    conducted: '①실시하다 ②수행하다',
    contexts: '①문맥 ②상황',
    countless: '①많은 ②셀 수 없는',
    elicited: '①이끌어 내다 ②끌어내다',
    frequency: '①주파수 ②빈도',
    increase: '①증가하다 ②늘리다',
    intensity: '①강도 ②강렬함',
    involves: '관련시키다',
    premise: '①전제 ②건물',
    recall: '①상기하다 ②기억하다',
    reference: '①참고 ②기준',
    solely: '①오로지 ②오직',
    technique: '①기법 ②기술',
    variable: '①변화하는 ②변수',
    vowel: '모음',
    applied: '①적용된 ②응용의',
    compounds: '화합물',
    concentration: '①농축 ②집중',
    conditioned: '①조건부의 ②조절된',
    constituents: '구성 요소들',
    contaminated: '①오염된 ②방사성 물질에 오염된',
    disposal: '①처리 ②처분',
    disposed: '①경향이 있는 ②마음이 나는',
    extraction: '①뽑아냄 ②추출',
    hence: '①그러므로 ②앞으로',
    immobilized: '①움직이지 않게 하다 ②고정시키다',
    industry: '①산업 ②업계',
    inherent: '①내재된 ②고유의',
    mineral: '①광물 ②무기질',
    presumes: '①추정하다 ②전제로 하다',
    radiation: '①방사 ②복사',
    radioactive: '①방사성 ②방사능',
    radionuclides: '무담체 방사성핵종',
    recovered: '회복한',
    recovery: '①회복 ②회수',
    reprocessing: '①재가공하다 ②재생하다',
    substituted: '대체하다',
    affordance: '지원성',
    anti: '①반대 ②반',
    aspect: '①양상 ②측면',
    atomic: '①원자의 ②핵무기',
    blockage: '①봉쇄 ②방해',
    discoverable: '①발견할 수 있는 ②인정될 수 있는',
    injure: '①부상을 입히다 ②상처를 입히다',
    interaction: '①상호 작용 ②관계',
    invisibility: '①눈에 보이지 않음 ②불가시성',
    particles: '①입자 ②먼지',
    passage: '①통과 ②통로',
    perceivable: '①지각할 수 있는 ②인지할 수 있는',
    perceived: '①인지하다 ②인식하다',
    presence: '①존재 ②영향력',
    prevention: '①예방 ②방지',
    structure: '①구조 ②구성하다',
    transparency: '①투명도 ②투명',
    aspects: '①양상 ②측면',
    bland: '①온화한 ②개성없는',
    communicative: '①통신의 ②소통하는',
    contexts: '①문맥 ②상황',
    distribution: '①분포 ②분배',
    formal: '①공식적인 ②정식의',
    formulas: '①공식 ②방식',
    function: '①기능 ②역할',
    portion: '①부분 ②일부',
    ritual: '①의식 ②제사',
    transactions: '①거래 ②트랜잭션',
    transmitted: '①부치다 ②옮기다',
    urged: '①충동 ②열망',
    verbally: '①말로 ②구두로',
    accidental: '①우발적인 ②우연한',
    behaviour: '행동',
    concluded: '결론짓다',
    conducted: '①실시하다 ②수행하다',
    explanation: '①설명 ②해명',
    hypothesis: '①가설 ②가정',
    limited: '①한정된 ②제한을 받은',
    phenomenon: '①현상 ②장관',
    reinforce: '①보강하다 ②강화하다',
    release: '①발표하다 ②개봉하다',
    ritualistic: '①의례적인 ②관습적인',
    rituals: '①의식 ②제사',
    whatsoever: 'whatever의 강조형',
    category: '①범주 ②부문',
    consist: '①이루어지다 ②구성되다',
    constituents: '구성 요소들',
    criteria: '①기준 ②평가',
    distinctive: '①독특한 ②특유의',
    domain: '①분야 ②영토',
    entirety: '①완전한 상태 ②전부',
    entities: '①실체 ②본질',
    existence: '①존재 ②현존',
    extension: '①확장 ②연장',
    fundamentally: '①근본적으로 ②기본적으로',
    identical: '①똑같은 ②동일한',
    identity: '①정체성 ②자신',
    individuated: '개체화하다',
    membership: '회원',
    nonindividuated: '개인화 되지 않은',
    ontological: '①존재론적인 ②존재론의',
    portion: '①부분 ②일부',
    referring: '언급하다',
    sameness: '①단조로움 ②동일',
    scattered: '①뿌려진 ②흩어져 있는',
    substances: '①물질 ②내용',
    wholeness: '①전체 ②총체',
    admirable: '①감탄할만한 ②훌륭한',
    adopt: '①채택하다 ②입양하다',
    airwaves: '방송',
    brutal: '①잔인한 ②무자비한',
    dominant: '①지배적인 ②우세한',
    endangered: '①멸종 위기의 ②위험한',
    extinct: '①멸종한 ②사라진',
    globalization: '①세계화 ②국제화',
    hostility: '①적개심 ②적대',
    indigenous: '①고유의 ②토착의',
    intense: '①강렬한 ②심한',
    intimidating: '①무서워하는 ②벌벌 떠는',
    lifelines: '①구명 밧줄 ②주요 도로',
    mainstream: '①주류 ②대세',
    minority: '소수',
    preservation: '①보존 ②보전',
    repression: '①탄압 ②억제',
    retaining: '①유지하다 ②보유하다',
    reverse: '①반대의 ②뒤집다',
    revitalizing: '새로운 활력을 주다',
    revive: '①소생시키다 ②되살아나다',
    belongingness: '①소속됨 ②소유',
    conform: '①순응하다 ②따르다',
    consistent: '①일관된 ②지속적인',
    eventually: '①결국 ②마침내',
    excluded: '①제외하다 ②배제하다',
    increase: '①증가하다 ②늘리다',
    individuals: '개인들',
    motive: '①동기 ②의도',
    ostracism: '①추방 ②배척',
    ostracized: '추방하다',
    perceptions: '①인식 ②지각',
    reconnect: '①다시 연결 ②다시 연락',
    rejected: '①거절하다 ②버리다',
    rejection: '①거부반응 ②거부',
    relevant: '①관련있는 ②적절한',
    retention: '①보유 ②기억',
    seek: '①추구하다 ②찾다',
    subsequent: '①뒤의 ②다음의',
    autopilot: '자동 조종 장치',
    cognitive: '①인식의 ②인지의',
    detail: '①세부 ②상세',
    engagement: '①참여 ②연대',
    fascinating: '매료된',
    induces: '①유발하다 ②유도하다',
    intricate: '①복잡한 ②미묘한',
    laptop: '①노트북 ②휴대용 컴퓨터',
    mechanics: '①역학 ②기계학',
    minded: '①ㅇㅇ한 마음을 가진 ②ㅇㅇ에 흥미가 있는',
    mindfulness: '①명상 ②주의 깊음',
    neuroscience: '신경 과학',
    onslaught: '①맹공격 ②맹습',
    openness: '①개방성 ②솔직',
    plugged: '플러그를 꽂다',
    qualities: '①특성 ②성질',
    reinforce: '①보강하다 ②강화하다',
    technological: '기술적인',
    thriving: '①번영하는 ②번성하는',
    advantage: '①이점 ②우위',
    colony: '①식민지 ②집단',
    cycle: '①주기 ②순환',
    drift: '①떠다니다 ②멀어지다',
    jammed: '①빽빽한 ②가득찬',
    larvae: '①유충 ②무척추 동물의 새끼',
    scattered: '①뿌려진 ②흩어져 있는',
    settle: '①해결하다 ②정착하다',
    sperms: '①정액 ②정자',
    squirt: '뿜어나오다',
    tadpole: '올챙이',
    altering: '①변하다 ②바뀌다',
    appraisal: '①평가 ②감정',
    aspect: '①양상 ②측면',
    attack: '①공격하다 ②발작',
    attitude: '①태도 ②자세',
    bowled: '①굴리다 ②순조롭게 진행되다',
    coworker: '①일의 동료 ②협력자',
    fulfilling: '①이루다 ②이행하다',
    halo: '①후광 ②영광',
    individual: '개인의',
    nobler: '①고귀한 ②귀족의',
    noticeable: '①눈에 띄는 ②주목할 만한',
    obnoxious: '①불쾌한 ②밉살스러운',
    perceptions: '①인식 ②지각',
    specific: '①특정한 ②구체적인',
    trait: '①특징 ②특성',
    trustworthy: '신뢰할 수 있는',
    unconsciously: '①부지불식간에 ②무의식적으로',
    warmth: '①따뜻함 ②온기',
    aptly: '①적절히 ②적절하게',
    bloodstream: '①혈류 ②활력',
    bubble: '①거품 ②기포',
    dissolve: '①녹이다 ②없애다',
    frothing: '①거품을 내뿜다 ②거품이 일다',
    joints: '①공동의 ②관절',
    nitrogen: '질소',
    soluble: '①녹는 ②해결할 수 있는',
    substituted: '대체하다',
    acres: '토지 면적의 단위',
    admitted: '①인정된 ②시인',
    appointed: '①임명하다 ②지명하다',
    aware: '①알고 있는 ②인식하는',
    beneath: '①아래에 ②밑에',
    clamored: '①외치다 ②떠들어대다',
    cliffland: '①손에 땀을 쥐는 상태로 끝나다 ②불안한 상태에 놓이다',
    commission: '①위원회 ②수수료',
    eroded: '①침식하다 ②부식하다',
    erosional: '①침식의 ②풍화의',
    existence: '①존재 ②현존',
    geologists: '지질학자',
    preventive: '①예방의 ②예방약',
    processes: '①처리하다 ②과정',
    spectacular: '①장관의 ②화려한',
    accelerate: '가속하다',
    adapt: '①적응하다 ②변화',
    applied: '①적용된 ②응용의',
    cohere: '①밀착하다 ②응집하다',
    converted: '①전환하다 ②바꾸다',
    differ: '①다르다 ②차이',
    distorted: '①왜곡하다 ②뒤틀다',
    elastic: '①탄력 있는 ②신축성이 있는',
    equal: '①평등한 ②동등한',
    extent: '①정도 ②범위',
    facility: '①시설 ②설비',
    immersed: '①잠긴 ②묻힌',
    isotropic: '등방성의',
    leak: '①유출 ②새다',
    tendency: '①경향 ②추세',
    unconstrained: '①구속되지 않은 ②자유로운',
    urge: '①촉구하다 ②요구하다',
    vessel: '①선박 ②혈관',
    comprehensive: '①종합적인 ②포괄적인',
    depicts: '①표현하다 ②나타내다',
    integral: '①완전한 ②필수의',
    interpreted: '①뜻을 밝히다 ②해석하다',
    intriguing: '①음모를 꾸미다 ②끌다',
    straightforward: '①직접의 ②솔직한',
    subjectivity: '①주관성 ②주관적임',
    terms: '①용어 ②기간',
    acid: '①산 ②신',
    applying: '①적용하다 ②지원하다',
    attacks: '공격하다',
    beeches: '너도밤나무',
    browsing: '띄엄띄엄 읽다',
    compounds: '화합물',
    defensive: '①방어적인 ②수세의',
    detect: '①찾아내다 ②감지하다',
    discouraged: '①낙담한 ②의욕을 잃어버린',
    dripped: '물방울을 흘리다',
    heal: '①치유되다 ②치료하다',
    investigate: '①조사하다 ②수사하다',
    presence: '①존재 ②영향력',
    production: '①생산 ②제작',
    salicylic: '살리실산의',
    simulate: '모의 실험하다',
    wounded: '①상처를 입은 ②부상자',
    ancestor: '①조상 ②선조',
    ancestral: '①조상의 ②대대로 내려오는',
    assume: '①가정하다 ②생각하다',
    characteristics: '①특성 ②독특한',
    definition: '①정의 ②개념',
    descended: '①물려받은 ②내려온',
    estimates: '①추정하다 ②예상하다',
    genetics: '①유전학 ②유전적 특징',
    indicates: '①나타내다 ②가리키다',
    linguistic: '언어의',
    linguists: '언어학자',
    remnants: '①나머지 ②단편',
    afterward: '①그후 ②곧 이어',
    constant: '①일정한 ②지속적인',
    decline: '①감소하다 ②거절하다',
    defensively: '①방어적으로 ②수비에 서서',
    disdain: '①경멸하다 ②경멸',
    formative: '①형성의 ②발달의',
    fundamentally: '①근본적으로 ②기본적으로',
    fuss: '①소란 ②야단법석',
    hostility: '①적개심 ②적대',
    originate: '①유래하다 ②발생하다',
    parental: '①부모의 ②부모다운',
    applications: '①적용 ②응용',
    claimed: '①주장하다 ②말하다',
    competing: '①경쟁하다 ②경기하다',
    compromised: '①타협하다 ②절충하다',
    conducted: '①실시하다 ②수행하다',
    conflicts: '①갈등 ②분쟁',
    constitute: '①구성하다 ②간주하다',
    controversy: '①논란 ②논쟁',
    corporation: '①기업 ②회사',
    defense: '①국방 ②방어',
    establish: '①설립하다 ②세우다',
    eventually: '①결국 ②마침내',
    firms: '회사',
    funded: '①자금 ②소지금',
    genetic: '유전적인',
    genome: '게놈',
    genomics: '유전체학',
    innumerable: '①셀 수 없이 많은 ②무수한',
    inventory: '①재고 ②목록',
    issuing: '①논점 ②발행',
    joint: '①공동의 ②관절',
    laboratory: '①연구실 ②실험실',
    norm: '①규범 ②기준',
    openness: '①개방성 ②솔직',
    patents: '①특허 ②공유지 양도 증서',
    profit: '①이익 ②수익',
    publication: '①출판 ②간행물',
    raged: '①분노하다 ②격노하다',
    rival: '①경쟁하는 ②경쟁자',
    sector: '①부문 ②분야',
    sequences: '①서열 ②순서',
    sponsorship: '후원',
    suspended: '①중단하다 ②유예하다',
    accurately: '①정확하게 ②그대로',
    arranged: '①계획된 ②결정된',
    chunk: '①규모가 큰 ②큰 덩어리',
    complex: '①복잡한 ②복합의',
    declining: '①감소하다 ②거절하다',
    feat: '①위업 ②공적',
    glancing: '①언뜻 보다 ②번득이다',
    grandmasters: '최고 수준의 체스 선수',
    inputs: '①입력 ②산업',
    psychologists: '①심리학자 ②정신과 의사',
    recalled: '①상기하다 ②기억하다',
    receding: '①후퇴하다 ②몸을 빼다',
    retrieve: '①회수 ②되찾다',
    schema: '①개요 ②선험적 도식',
    technique: '①기법 ②기술',
    terms: '①용어 ②기간',
    alert: '①경계 ②주의하다',
    appendages: '①첨가물 ②부속 기관',
    biological: '①생물학의 ②생물학적 약제',
    cognitive: '①인식의 ②인지의',
    compels: '억지로 ㅇㅇ하게하다',
    consistently: '①일관되게 ②지속적으로',
    cope: '①대처하다 ②다루다',
    desire: '①욕망 ②싶다',
    efficient: '효율적인',
    engage: '①관여하다 ②약혼하다',
    established: '①설립하다 ②세우다',
    evaluations: '①평가 ②분석',
    evolutionary: '①발전의 ②진화론에 의한',
    fades: '염색이 바래다',
    farthest: '①가장 ②가장 먼',
    genetics: '①유전학 ②유전적 특징',
    immature: '①미숙한 ②유년기의',
    indeed: '①정말로 ②사실은',
    infant: '①유아의 ②초기의',
    involve: '①관련되다 ②참여하다',
    novelty: '①새로움 ②신기함',
    parenthood: '①어버이임 ②어버이의 입장',
    paychecks: '①봉급 ②급료',
    predictability: '예상 가능함',
    preference: '①선호 ②좋아하기',
    processes: '①처리하다 ②과정',
    propensity: '①경향 ②성향',
    reaches: '①도착하다 ②미치다',
    releasing: '①해방하다 ②떼어놓다',
    seek: '①추구하다 ②찾다',
    survival: '①생존 ②살아남기',
    unfamiliar: '①낯선 ②익숙지 않은',
    bacterial: '세균의',
    colonies: '①식민단 ②식민지',
    colony: '①식민지 ②집단',
    consulting: '①조언을 청하다 ②참고하다',
    crisis: '①위기 ②문제',
    critical: '①비판적인 ②중요한',
    doubt: '①의심하다 ②의혹',
    extraordinarily: '①몹시 ②이례적으로',
    hyper: '①하이퍼 ②과잉',
    hypermutation: '①치환 ②순열',
    hypermutators: '고돌연변이 유발 유전자',
    infinitely: '①무한히 ②한없이',
    insane: '①미친 ②정신 이상의',
    involves: '관련시키다',
    mess: '①엉망 ②혼란',
    microbial: '①미생물의 ②세균의',
    mutate: '①변화시키다 ②돌연변이시키다',
    mutating: '①변화시키다 ②모음 변화시키다',
    mutation: '①변화 ②돌연변이',
    organism: '①생물 ②유기체',
    precisely: '①정확히 ②정밀하게',
    survival: '①생존 ②살아남기',
    approval: '①승인 ②허가',
    associations: '①협회 ②관련',
    attach: '①포함하다 ②부착하다',
    ceremonies: '①의식 ②예의',
    claim: '①주장하다 ②말하다',
    colleague: '동료',
    complementary: '①보완적인 ②대체',
    complex: '①복잡한 ②복합의',
    consist: '①이루어지다 ②구성되다',
    contributed: '①기부하다 ②기고하다',
    cooperation: '협력',
    criminals: '①범죄자 ②범죄의',
    defined: '정의된',
    deprivation: '①박탈 ②결핍',
    deviant: '①벗어난 ②비정상적인 사람',
    disapproval: '①반대 ②비난',
    discredit: '①의심하다 ②신용하지 않다',
    displeasure: '①불만 ②화남',
    doubt: '①의심하다 ②의혹',
    excluded: '①제외하다 ②배제하다',
    exclusion: '①배제 ②제외',
    formal: '①공식적인 ②정식의',
    formalization: '①형식화 ②의례',
    formalized: '형식화하다',
    gossip: '①소문 ②험담',
    indicating: '①나타내다 ②가리키다',
    informal: '①비공식 ②비형식',
    judging: '①재판관 ②심사원',
    maintained: '①유지하다 ②계속하다',
    membership: '회원',
    minimal: '①최소의 ②아주 작은',
    norms: '①규범 ②기준',
    obligation: '①의무 ②채무',
    procedures: '①절차 ②과정',
    reciprocating: '①보답하다 ②교환하다',
    refusal: '①거부 ②거절',
    reinforced: '①보강하다 ②늘리다',
    retain: '①유지하다 ②보유하다',
    ridicule: '①조롱하다 ②놀리다',
    sanctions: '①허가 ②구속',
    sociologists: '사회학자',
    spontaneous: '①자연스러운 ②자발적인',
    structure: '①구조 ②구성하다',
    violate: '①위반하다 ②침해하다',
    violator: '①위반자 ②위배자',
    applied: '①적용된 ②응용의',
    banyan: '①반얀나무 ②벵골보리수',
    branches: '①가지 ②분과',
    chewed: '씹다',
    cuoi: '결혼하다',
    frightful: '①무시무시한 ②놀랄만한',
    grasped: '①이해하다 ②잡다',
    growl: '①으르렁거리다 ②꼬르륵거리다',
    handful: '①소수의 ②몇몇의',
    haste: '①서두르다 ②성급함',
    miraculous: '①초자연적인 ②기적의',
    offspring: '①자식 ②새끼',
    predicament: '①곤경 ②곤란함',
    pulp: '①과육 ②걸쭉한 것',
    replanted: '①옮겨 심다 ②재이식하다',
    scrambled: '①기어오르다 ②서로 가지려 하다',
    tigress: '①호랑이의 암컷 ②잔인한 여자',
    underbrush: '①덤불 ②관목',
    uprooted: '①뿌리째 뽑히다 ②근절되다',
    accurate: '①정확한 ②정밀한',
    aware: '①알고 있는 ②인식하는',
    barred: '①빗장으로 잠근 ②줄가 있는',
    branch: '①가지 ②지점',
    businesslike: '①사무적인 ②신속한',
    clenched: '①꽉 닫히다 ②꽉 쥐다',
    constant: '①일정한 ②지속적인',
    demonstrate: '①증명하다 ②입증하다',
    dramatic: '①극적인 ②급격한',
    elected: '①선출된 ②당선된',
    endured: '①견디어 내다 ②견디다',
    fists: '①주먹 ②움켜쥐다',
    handshake: '악수',
    honored: '①명예로운 ②영광으로 생각하여',
    hostility: '①적개심 ②적대',
    humbled: '①겸손한 ②열등감을 느끼는',
    latter: '①후자의 ②하반기의',
    league: '①리그 ②연맹',
    massive: '①대규모의 ②거대한',
    opposing: '①적대하는 ②정반대의',
    patience: '①인내 ②참을성',
    portrayal: '①묘사 ②묘사된 것',
    prediction: '①예측 ②추정',
    pretended: '①자칭의 ②거짓의',
    prominent: '①유명한 ②두드러진',
    qualify: '①자격을 갖추다 ②자격을 얻다',
    racist: '인종 차별주의자',
    referring: '언급하다',
    resentment: '①분노 ②적의',
    rookie: '①신인 선수 ②루키',
    sainthood: '①성인의 신분 ②성인임',
    teammates: '①팀의 한 사람 ②단원',
    threateningly: '①위협적으로 ②협박하듯이',
    unclenched: '펴다',
    aback: '①역풍을 받은 ②돛이 앞바람을 받고',
    awakened: '①깨다 ②각성하다',
    barked: '①나무 껍질 ②짖다',
    cash: '①현금 ②돈',
    compassion: '①동정 ②연민',
    confusion: '①혼란 ②혼동',
    consideration: '①고려 ②배려',
    cops: '①잡히기 ②붙잡다',
    cupboard: '①찬장 ②벽장',
    disciple: '①제자 ②문하생',
    emptied: '①빈 ②비우다',
    gaunt: '①여윈 ②황량한',
    hooded: '①후드 ②모자',
    investigate: '①조사하다 ②수사하다',
    jail: '①감옥 ②징역',
    robbing: '①빼앗다 ②훔치다',
    shrine: '①성지 ②사당',
    silhouette: '①윤곽 ②실루엣',
    admiration: '①존경 ②감탄',
    applies: '①적용하다 ②지원하다',
    attacking: '공격하다',
    behaviorists: '①행동주의 심리학자 ②행동주의적인',
    contempt: '①경멸 ②모욕',
    cryptophthalmos: '잠복고환',
    delight: '①기쁘게 하다 ②기쁨',
    disabilities: '읽기 이해장애',
    disability: '①무력 ②무능',
    doubtful: '①의심스러운 ②회의적인',
    eyelids: '눈꺼풀',
    flock: '①모이다 ②떼짓다',
    grooming: '①신랑 ②털을 깨끗이 하다',
    indeed: '①정말로 ②사실은',
    inspiring: '①영감 ②고무',
    lame: '①절름발이의 ②서투른',
    perch: '①높은 곳 ②앉다',
    sturla: '①돌기둥 ②기념 석주',
    triumphant: '①의기양양한 ②성공한',
    unfortunate: '①불행한 ②유감스러운',
    allingham: '질링엄',
    anthologies: '①명시선 ②명시선',
    befriended: '①친구가 되다 ②돕다',
    bloomfield: '블룸필드',
    county: '①군 ②주',
    critic: '①비평가 ②비판가',
    dedicated: '①헌신적인 ②전용의',
    eventually: '①결국 ②마침내',
    excise: '①소비세 ②삭제하다',
    influential: '①영향력있는 ②유력한',
    promote: '①홍보하다 ②승진시키다',
    reform: '①개혁 ②개선',
    settled: '①안정된 ②정착한',
    tenants: '①점유하다 ②거주하다',
    blades: '①블레이드 ②날',
    bore: '①지루하게 하다 ②따분하게 하다',
    chewed: '씹다',
    constructed: '①만들다 ②건설하다',
    corkscrew: '①코르크 마개뽑이 ②나선 모양으로 나아가다',
    debtor: '①채무자 ②차주',
    drill: '①훈련 ②뚫다',
    dug: '①dig의 과거 과거 분사형 ②젖꼭지',
    eventually: '①결국 ②마침내',
    excreting: '①배설하다 ②분비하다',
    fled: 'flee의 과거 과거 분사형',
    observation: '①관찰 ②관측',
    pedestrians: '①보행의 ②도보의',
    pulp: '①과육 ②걸쭉한 것',
    shipworm: '①배좀벌레조개 ②좀조개',
    targeted: '①과녁 ②달성 목표',
    unsuspecting: '①의심하지 않는 ②신용하는',
    wapping: '①휙 끌어당기다 ②내던지다',
    assistant: '①보조 ②조수',
    astronomer: '①천문학자 ②천문대장',
    calibration: '①구경측정 ②눈금',
    convinced: '①확신하는 ②설득했다',
    depended: '의존하다',
    discrepancy: '①불일치 ②차이',
    dismissed: '①해산시키다 ②해임하다',
    error: '①오차 ②오류',
    observations: '①관찰 ②관측',
    stellar: '①별의 ②별 같은',
    striven: '①노력하다 ②싸우다',
    transits: '①통과 ②운송',
    allergic: '①알레르기의 ②알레르기가 있는',
    gotten: '걸린',
    manmade: '①인공의 ②사람이 만든',
    adoption: '①채용 ②채택',
    agricultural: '①농업의 ②농산의',
    anthropologists: '인류학자',
    civilization: '문명',
    domesticated: '①가축화한 ②길들인',
    fundamental: '①기본적인 ②근본적인',
    marginal: '①가장자리의 ②경계의',
    occasionally: '①가끔 ②때때로',
    permitted: '①허용하다 ②인가',
    plots: '①음모 ②줄거리',
    sedentary: '①앉아서 하는 ②앉아 있는',
    settle: '①해결하다 ②정착하다',
    utilize: '①활용하다 ②이용하다',
    categorization: '①분류 ②범주화',
    division: '①부 ②분단',
    domain: '①분야 ②영토',
    era: '①시대 ②시절',
    fleeting: '①덧없는 ②어느덧 지나가는',
    formulated: '공식화하다',
    framework: '①근거 ②체제',
    irrational: '①비이성적인 ②비합리적인',
    latter: '①후자의 ②하반기의',
    necessity: '①필요성 ②필수품',
    philosopher: '철학자',
    provable: '①증명할 수 있는 ②입증할 수 있는',
    rational: '①합리적인 ②이성적인',
    undefinable: '①막연한 ②한정할 수 없는',
    unprovable: '①증명할 수 없는 ②실증할 수 없는',
    unraveling: '①풀리다 ②해명되다',
    ushered: '①안내를 맡다 ②안내하다',
    visible: '①보이는 ②가시의',
    affluent: '①부유한 ②유복한',
    confirmation: '①확인 ②확증',
    consequence: '①결과 ②대가',
    crest: '①벼슬 ②크레스티드',
    ethnic: '①민족의 ②혈통의',
    glow: '①빛나다 ②불이 켜지다',
    icon: '①아이콘 ②우상시 되는 인물',
    individuals: '개인들',
    innovation: '①혁신 ②획기적인',
    maintain: '①유지하다 ②계속하다',
    mask: '①마스크 ②가면',
    needless: '①불필요한 ②쓸데없는',
    primitive: '①원시의 ②원초적인',
    prosperous: '①번영하는 ②성공한',
    reasserted: '거듭 주장하다',
    rediscovery: '①재발견 ②재발견된 것',
    seek: '①추구하다 ②찾다',
    societal: '①사회의 ②사회 활동의',
    visual: '①시각의 ②눈에 보이는',
    weatherboards: '①물막이판을 대다 ②물막이판',
    beneath: '①아래에 ②밑에',
    chapters: '①장으로 나누다 ②장 지부',
    dimensions: '①크기',
    discipline: '①학문 ②규율',
    eras: '①시대 ②연대',
    geologically: '지질학적으로',
    geologists: '지질학자',
    geology: '지질학',
    illumination: '①조명 ②전등 장식',
    imperfect: '①불완전한 ②불충분한',
    inscribed: '①이름 등을 써서 증정하다 ②기명하다',
    invariably: '①반드시 ②언제나',
    landforms: '지형발달사',
    medieval: '중세의',
    palimpsest: '①한 번 쓴 것을 지운 ②뒷면에도 문자를 조각한',
    parchment: '①양피지 ②양피지 사본',
    perceive: '①인지하다 ②인식하다',
    remnants: '①나머지 ②단편',
    scraped: '①문지르다 ②난폭하게 비비다',
    subsurface: '①표면하의 ②표면 아래의',
    techniques: '①기법 ②기술',
    term: '①용어 ②기간',
    traces: '①자취 ②자취',
    visible: '①보이는 ②가시의',
    associated: '①연관된 ②관계가 있는',
    consequence: '①결과 ②대가',
    consists: '①이루어지다 ②구성되다',
    conveyor: '운반 장치',
    decade: '①십년간 ②수십년',
    disaster: '①재난 ②재앙',
    equator: '적도',
    freshwater: '①담수의 ②민물의',
    ironic: '역설적인',
    saltwater: '①소금물의 ②해산의',
    shutdown: '①폐쇄하다 ②닫다',
    tipping: '기울다',
    trigger: '①촉발 ②유발하다',
    affect: '①영향을 주다 ②작용하다',
    arch: '①아치 ②활모양의',
    bonanza: '①풍부한 광맥 ②대풍년',
    ecological: '①생태학적 ②환경 친화적인',
    enrich: '부유하게 하다',
    gap: '①간격 ②차이',
    grizzly: '①회색이 도는 ②심한',
    habitat: '①서식지 ②생태',
    impacted: '영향을 받은',
    inland: '①내륙의 ②국내의',
    keystone: '①쐐기돌 ②근본 원리',
    lack: '①부족 ②ㅇㅇ이 없다',
    ladders: '①사다리 ②오르는 길',
    limited: '①한정된 ②제한을 받은',
    nutrients: '영양',
    obstacles: '①장애 ②방해',
    oceanic: '①대양의 ②대양에 사는',
    schemes: '①계획하다 ②계획하다',
    spawning: '①산란 ②채란',
    upstream: '상류로',
    vegetation: '①초목 ②식물',
    acid: '①산 ②신',
    acidified: '산성화하다',
    brief: '①보고서 ②짧은',
    calcium: '칼슘',
    caldeira: '대형 분화구',
    carbonate: '①탄산염 ②탄산염화하다',
    dinosaurs: '공룡',
    ensued: '①계속되다 ②결과로서 일어나다',
    extinct: '①멸종한 ②사라진',
    fossil: '①화석 ②시대에 뒤진 사람',
    handful: '①소수의 ②몇몇의',
    imprint: '①찍다 ②자국',
    meteor: '①유성 ②별똥별',
    rare: '①희귀한 ②드문',
    reappear: '①재현하다 ②다시 나타나다',
    scarce: '①부족한 ②희귀한',
    skeletons: '골격',
    slammed: '쾅 닫다',
    sulfur: '유황의',
    absorb: '①흡수하다 ②열중하다',
    acoustic: '①청각의 ②소리의',
    aesthetic: '미학의',
    backdrop: '①배경막 ②배경막을 달다',
    bio: '①생물학 ②자서전',
    corridor: '복도',
    determined: '①결정된 ②결심한',
    discreet: '①신중한 ②분별력 있는',
    exceptions: '①예외 ②특례',
    facade: '①정면 ②외관',
    identical: '①똑같은 ②동일한',
    identity: '①정체성 ②자신',
    integrate: '①통합하다 ②포함하다',
    merge: '①통합하다 ②합병하다',
    neighbouring: '①근처에 사는 ②인근의',
    transparent: '①투명한 ②속보이는',
    assumption: '①가정 ②추측',
    basically: '기본적으로',
    biases: '①비스듬한 ②비스듬히',
    budge: '움직이기 시작하다',
    complicated: '①복잡한 ②어려운',
    conjure: '①떠올리다 ②불러일으키다',
    equal: '①평등한 ②동등한',
    fallacies: '①오류 ②착오',
    laypeople: '①일반인 ②비전문가',
    naked: '①벌거벗은 ②나체의',
    narrative: '①설명적인 ②이야기',
    randomness: '①무작위 ②우연성',
    rearranged: '①다시 배열하다 ②전위하다',
    recede: '①멀어지다 ②감소하다',
    reflected: '①반사하다 ②보여주다',
    boundary: '①경계 ②영역',
    conduction: '①전도 ②끎',
    conductor: '①지휘자 ②전도체',
    deficit: '①적자 ②결손',
    molecules: '분자',
    separating: '①가르다 ②헤어지게 하다',
    thermal: '①열의 ②뜨거운',
    windless: '①숨이 찬 ②바람이 없는',
    chill: '①냉각하다 ②무서운',
    credited: '①신용 ②명성',
    demonstrating: '①논증하다 ②명시하다',
    escapade: '①엉뚱한 짓 ②분별없는 장난',
    extend: '①확장하다 ②연장하다',
    highgate: '높은 비율',
    martyr: '①순교자 ②순국자',
    organs: '①오르간 ②기관',
    pneumonia: '폐렴',
    polymath: '박식가',
    refrigeration: '①냉각 ②냉동',
    relevant: '①관련있는 ②적절한',
    remarkable: '①놀라운 ②주목할 만한',
    spontaneous: '①자연스러운 ②자발적인',
    unrecorded: '기록되지 않은',
    unsuitably: '적절치 않게',
    adapt: '①적응하다 ②변화',
    agroforestry: '①삼림 농업 ②농림업',
    basis: '①기초 ②근거',
    climatic: '①기후의 ②기후에 의한',
    depth: '①깊이 ②심도',
    diversity: '①다양성 ②상이',
    domesticated: '①가축화한 ②길들인',
    domestication: '①길들이기 ②정듦',
    enabled: '가능하게하다',
    estimates: '①추정하다 ②예상하다',
    evolution: '①진화 ②변화',
    fibre: '①섬유 ②섬유질',
    genetic: '유전적인',
    heritable: '상속할 수 있는',
    individuals: '개인들',
    involves: '관련시키다',
    majority: '①다수의 ②대부분',
    plantations: '①농장 ②조림지',
    regarded: '①간주하다 ②생각하다',
    selection: '①선택 ②선발',
    tropics: '①열대 지방의 ②열대성의',
    undergone: 'undergo의 과거 분사형',
    undescribed: '기술 되지 않은',
    captivity: '①속박 ②감금',
    carnivores: '육식 동물',
    charges: '①청구하다 ②부담으로 하다',
    depriving: '①박탈하다 ②빼앗다',
    distasteful: '①싫은 ②불쾌한',
    flee: '①도망치다 ②피하다',
    foraging: '수렵 채집',
    predominant: '①우세한 ②지배적인',
    replicate: '①모사하다 ②복제하다',
    replicating: '①반복되는 ②많은',
    unearned: '①과분한 ②노력 없이 얻은',
    unnatural: '부자연스러운',
    allotment: '①분배 ②할당',
    cruise: '①크루즈 ②유람선',
    depth: '①깊이 ②심도',
    disadvantage: '①불리 ②불리하게 하다',
    historic: '①역사적인 ②사',
    itineraries: '①여로 ②여행의',
    limited: '①한정된 ②제한을 받은',
    majority: '①다수의 ②대부분',
    peeve: '①약올리다 ②불평',
    resort: '①리조트 ②의존하다',
    specialized: '①전문의 ②분화한',
    apparently: '①분명히 ②명백히',
    chuck: '①척 ②던지다',
    concluded: '결론짓다',
    definitely: '①분명히 ②확실하게',
    hardaway: '①고생해서 ②엄격하게',
    league: '①리그 ②연맹',
    reinforcement: '①보강 ②강화',
    slump: '①폭락 ②푹 쓰러지다',
    streak: '①연속 ②계속',
    accomplishment: '①성취 ②업적',
    achieving: '①성과를 올리다 ②성취하다',
    aesthetic: '미학의',
    automatically: '①자동적으로 ②자연히',
    considerably: '①많이 ②상당히',
    context: '①문맥 ②상황',
    criterion: '①기준 ②평가',
    established: '①설립하다 ②세우다',
    explanation: '①설명 ②해명',
    extraordinary: '①특별한 ②뛰어난',
    firmly: '①확고하게 ②강하게',
    function: '①기능 ②역할',
    indeed: '①정말로 ②사실은',
    instrument: '①악기 ②도구',
    performers: '연기자',
    rasping: '①쓰는 ②긁어대는',
    scraping: '①문지르다 ②난폭하게 비비다',
    tonal: '①음색의 ②색조의',
    varies: '다양하게 나타나다',
    angle: '①각도 ②관점',
    automatically: '①자동적으로 ②자연히',
    composition: '①구성 ②작문',
    compressing: '①압축하다 ②습포',
    consideration: '①고려 ②배려',
    defining: '①정의하다 ②경계를 정하다',
    depicted: '①묘사하다 ②그리다',
    diminish: '①낮아지다 ②줄어들다',
    emphasizing: '①강조하다 ②강세를 두다',
    evolved: '①발전하다 ②진전하다',
    formulas: '①공식 ②방식',
    imagemakers: '①광고를 하는 사람 ②이미지를 만드는 사람',
    knowledgeable: '①박식한 ②정통해 있는',
    linear: '①직선 모양의 ②길이에 관한',
    modified: '①완화된 ②수정된',
    obscura: '①어둠 상자 ②차광 상자',
    perspective: '①관점 ②시각',
    pictorial: '①그림의 ②그림으로 나타낸',
    predefined: '미리 정하다',
    procedures: '①절차 ②과정',
    radical: '①급진적인 ②과격한',
    represented: '①나타내다 ②ㅇㅇ의 대리를 하다',
    resembled: '①닮다 ②ㅇㅇ과 비슷하다',
    selection: '①선택 ②선발',
    sophisticated: '①정교한 ②복잡한',
    specific: '①특정한 ②구체적인',
    tonal: '①음색의 ②색조의',
    trace: '①추적하다 ②흔적',
    unchanged: '①불변의 ②변하지 않은',
    unforeseen: '①예기치 않은 ②뜻하지 않은',
    unintentional: '①본의 아닌 ②무심결의',
    unleash: '①놓아주다 ②ㅇㅇ의 속박을 풀다',
    abundant: '①풍부한 ②많은',
    architecture: '①건축 ②설계',
    availability: '①유용성 ②유효성',
    complexity: '①복잡함 ②난이도',
    conscious: '①의식한 ②친화적',
    conservation: '①보존 ②보호',
    conservative: '①보수적인 ②보수주의자',
    depended: '의존하다',
    effectiveness: '①효과적인 ②유효성',
    envelope: '봉투',
    expansive: '①팽창성 있는 ②광범위한',
    facades: '①정면 ②외관',
    fossil: '①화석 ②시대에 뒤진 사람',
    generosity: '①관대함 ②아낌없는',
    glazing: '①흐릿한 ②윤이 나는',
    insulation: '①절연체 ②단열재',
    reliance: '①신뢰 ②의존',
    retention: '①보유 ②기억',
    spatial: '①공간의 ②공간적인',
    tendencies: '①경향 ②성향',
    tightness: '①기밀 ②조임',
    ventilation: '①환기 ②환기 장치',
    agenda: '①의제 ②과제',
    appreciation: '①이해 ②감사',
    attractions: '①관광지 ②명소',
    composer: '①작곡가 ②작가',
    devised: '①고안하다 ②마련하다',
    evident: '①명백한 ②분명한',
    francophone: '①프랑스 어권 ②프랑스어를 말하는 주민',
    genre: '①장르 ②유형',
    identified: '①확인된 ②인정된',
    identities: '①동일함 ②본인임',
    idiosyncratic: '①특유한 ②특이한',
    itinerary: '①일정 ②기행',
    tourism: '①관광 ②여행',
    achieving: '①성과를 올리다 ②성취하다',
    approaches: '접근하다',
    archival: '기록 보관소의',
    archives: '①공문서 ②기록 보관소',
    bacterial: '세균의',
    critical: '①비판적인 ②중요한',
    facilitate: '①위하다 ②촉진하다',
    forgotten: '잊혀진',
    identify: '①확인하다 ②알아보다',
    implementing: '①도구 ②비품',
    innovation: '①혁신 ②획기적인',
    laboratory: '①연구실 ②실험실',
    strain: '①변형 ②종류',
    thrill: '①스릴 ②흥분',
    uncover: '①발견하다 ②밝히다',
    undergraduate: '①대학의 ②학부의',
    vehicle: '①차량 ②자동차',
    beaten: '①맞은 ②이긴',
    bleak: '①어두운 ②암담한',
    concluded: '결론짓다',
    conviction: '①확신 ②유죄 판결',
    credited: '①신용 ②명성',
    decades: '①십년간 ②수십년',
    determined: '①결정된 ②결심한',
    doomed: '①희망없는 ②실패한',
    extraordinary: '①특별한 ②뛰어난',
    imminent: '①절박한 ②임박한',
    nurture: '①육성하다 ②양육하다',
    overwhelming: '①압도하다 ②억누르다',
    seemingly: '①겉보기에는 ②언뜻 보기에',
    slum: '①빈민가 ②빈민굴',
    sociology: '①사회과학 ②사회학',
    surviving: '살아남아 있는',
    associations: '①협회 ②관련',
    broadly: '①광범위하게 ②거리낌없는',
    charitable: '①관대한 ②자비로운',
    expanded: '①확대하다 ②확장하다',
    gentiles: '①비유대인의 ②이교의',
    harbored: '①항구 ②품다',
    individuals: '개인들',
    jews: '①유대인 ②유대인의',
    nonrescuers: '비구조자들',
    prospective: '①예비의 ②장래의',
    rescuers: '구조자들',
    similarity: '①유사점 ②비슷함',
    spectrum: '①스펙트럼 ②범위',
    attitude: '①태도 ②자세',
    consequence: '①결과 ②대가',
    grumbling: '①투덜거리는 ②불평하는',
    input: '①입력 ②산업',
    mess: '①엉망 ②혼란',
    neglect: '①무시 ②방치하다',
    resistance: '①저항 ②내성',
    unilateral: '①일방적인 ②한쪽만의',
    bane: '①죽음 ②파멸',
    demon: '①악마 ②귀재',
    desire: '①욕망 ②싶다',
    employment: '고용',
    essence: '①본질 ②정수',
    existence: '①존재 ②현존',
    gratification: '①만족 ②희열',
    immediate: '즉각적인',
    procrastinate: '①미루다 ②끌다',
    procrastination: '①지연 ②미루기',
    sacrificing: '①산 제물 ②희생',
    satisfying: '①만족시키다 ②충족시키다',
    term: '①용어 ②기간',
    apparel: '①의류 ②의복',
    categories: '①분류상의 구분 ②종류',
    category: '①범주 ②부문',
    ceremonial: '①의식 ②기념식',
    commitment: '①몰입 ②약속',
    functioning: '①기능 ②의식',
    gender: '①성별 ②성',
    groupings: '①그룹으로 나누기 ②배합',
    interact: '①작용하다 ②교류하다',
    occasions: '①경우 ②때',
    political: '①정치의 ②정당의',
    religiosity: '①광적인 신앙심 ②종교성',
    rituals: '①의식 ②제사',
    significant: '①중요한 ②상당한',
    societies: '사회',
    sorting: '①분류하다 ②정렬하다',
    spirited: '①씩씩한 ②ㅇㅇ의 정신을 지닌',
    stance: '①입장 ②자세',
    visually: '①시각적으로 ②시각에 관하여',
    addressed: '①다뤄진 ②다뤄지다',
    competence: '①능력 ②자신감',
    demands: '①요구하다 ②수요',
    diversity: '①다양성 ②상이',
    economic: '①경제의 ②경기의',
    educators: '①교육자 ②교사',
    engage: '①관여하다 ②약혼하다',
    envision: '①상상하다 ②마음에 그리다',
    equality: '①평등 ②동등',
    ethnic: '①민족의 ②혈통의',
    exist: '①존재하다 ②있다',
    immigration: '①이민 ②출입국 관리',
    impermeable: '①통과시키지 않는 ②빠져나갈 수 없는',
    indeed: '①정말로 ②사실은',
    intensified: '①격렬해지다 ②강해지다',
    linguistic: '언어의',
    paradigms: '①어형 변화예 ②패러다임',
    racial: '①인종의 ②민족의',
    societies: '사회',
    sustainable: '지속 가능한',
    transformation: '①전환 ②변화',
    unnoticed: '①주목받지 못하는 ②눈에 띄지 않는',
    visionary: '①환상의 ②공상적인',
    birthrate: '출생률',
    contribute: '①기여하다 ②공헌하다',
    correlation: '①상호 관계 ②상관 관계',
    fitness: '①건강 ②운동',
    flourishing: '①번영하는 ②성대한',
    inclusive: '①일체를 포함한 ②포괄적인',
    initially: '①처음에 ②당초에',
    inverse: '①반대의 ②역의',
    literacy: '①읽고 쓰는 능력 ②읽고 쓸 줄 앎',
    proxy: '①대리인 ②대리권',
    selected: '①선택된 ②선발된',
    selection: '①선택 ②선발',
    universal: '①보편적인 ②전 세계의',
    utilize: '①활용하다 ②이용하다',
    accessed: '접근하다',
    administration: '①정부 ②행정',
    advocates: '①옹호하다 ②주장하다',
    attempt: '①시도하다 ②노력',
    bureaucrat: '①관료 ②공무원',
    burgeoning: '①급증하는 ②급성장 하는',
    citizen: '①시민 ②국민',
    clients: '고객',
    commerce: '①상업 ②무역',
    conducting: '①실시하다 ②수행하다',
    convenience: '①편의 ②편리',
    democratize: '①민주화하다 ②민주적으로 하다',
    dramatic: '①극적인 ②급격한',
    governance: '①통치 ②지배',
    governmental: '①정치의 ②행정 기관의',
    individual: '개인의',
    modernize: '①현대화되다 ②근대화하다',
    presence: '①존재 ②영향력',
    provision: '①규정 ②조항',
    reformers: '①개량자 ②종교 개혁가',
    responsive: '①반응하는 ②대응하는',
    sector: '①부문 ②분야',
    align: '①일렬 ②관련',
    assistant: '①보조 ②조수',
    autonomous: '①자주적인 ②자율적인',
    conflict: '①갈등 ②분쟁',
    destinations: '①목적지 ②관광지',
    interacts: '①상호 작용하다 ②교류하다',
    internal: '①내부의 ②국내의',
    involved: '①관련된 ②관여하는',
    pedestrians: '①보행의 ②도보의',
    vehicles: '①차량 ②자동차',
    advertised: '①광고하다 ②홍보하다',
    advertisers: '①광고자 ②광고인',
    attachments: '①애착 ②부착',
    chronicled: '①연대기에 싣다 ②역사에 남기다',
    clown: '①광대 ②시골뜨기',
    commercial: '①상업용의 ②상업적인',
    enduring: '①참을성있는 ②지속하는',
    feature: '①특징 ②출연하다',
    featuring: '①보여준 ②등장',
    glamorous: '①매혹적인 ②매력이 넘치는',
    nurture: '①육성하다 ②양육하다',
    programmers: '프로그램 개발에 편리한 툴의 집합',
    specifically: '①특히 ②구체적으로',
    sponsored: '①ㅇㅇ후원의 ②자선 목적의',
    agency: '①기관 ②소속사',
    anonymous: '①익명의 ②이름을 밝히지 않은',
    bound: '①한계 ②묶인',
    consumer: '①소비자 ②고객',
    developers: '①개발자 ②계발자',
    disrupt: '①방해하다 ②피해를 주다',
    enables: '가능하게하다',
    hackers: '해커',
    individuals: '개인들',
    inquiries: '①사실을 구함 ②조사',
    intimate: '①친밀한 ②사적인',
    invasions: '①침략 ②침공',
    leaks: '①새는 곳 ②누전',
    secure: '①확보하다 ②안전한',
    security: '①보안 ②안보',
    servers: '①봉사자 ②서브하는 사람',
    specific: '①특정한 ②구체적인',
    trajectory: '①탄도 ②궤적',
    approach: '①접근하다 ②접근법',
    coactors: '①협력자 ②공동 작업자',
    cognitive: '①인식의 ②인지의',
    disrupt: '①방해하다 ②피해를 주다',
    embarrassment: '①당황 ②부끄러움',
    facilitation: '①용이하게 하기 ②간편화',
    favorable: '①유리한 ②호의적인',
    increase: '①증가하다 ②늘리다',
    individuals: '개인들',
    intensity: '①강도 ②강렬함',
    interference: '①간섭 ②방해',
    motivate: '①동기 부여 ②의욕',
    motivation: '①동기 부여 ②욕구',
    presence: '①존재 ②영향력',
    proposes: '①제안하다 ②제시하다',
    accomplished: '①성취하다 ②이루어 내다',
    achieving: '①성과를 올리다 ②성취하다',
    eventually: '①결국 ②마침내',
    greatness: '①위대함 ②탁월함',
    trail: '①둘레길 ②등산로',
    ultimately: '①마침내 ②결국',
    vitality: '①활력 ②생명력',
    worthwhile: '①가치있는 ②ㅇㅇ할 만한',
    affect: '①영향을 주다 ②작용하다',
    contagious: '①전염성의 ②감염병',
    encounters: '①만나다 ②마주치다',
    frustrating: '실망하는 듯한',
    fulfilling: '①이루다 ②이행하다',
    imbue: '①스며들게 하다 ②불어넣다',
    irritating: '①화난 ②안달이 난',
    painful: '①고통스러운 ②아픈',
    predict: '①예측하다 ②전망하다',
    prophecy: '①예언 ②예측',
    craftsmanship: '①손재주 ②솜씨',
    defensive: '①방어적인 ②수세의',
    elicit: '①이끌어 내다 ②끌어내다',
    guessed: '①ㅇㅇ인 것 같다 ②ㅇㅇ라고 생각하다',
    steer: '①조종하다 ②돌리다',
    appreciation: '①이해 ②감사',
    competing: '①경쟁하다 ②경기하다',
    eliminated: '①제거하다 ②실격시키다',
    firms: '회사',
    manufacturers: '①제조업자 ②업체',
    merged: '①합병하다 ②변하게 하다',
    railroads: '①철도에서 일하다 ②철도',
    regional: '①지역의 ②지방의',
    shipped: '①선박 ②십',
    slaughterhouses: '도살장',
    aesthetic: '미학의',
    applied: '①적용된 ②응용의',
    arising: '①일어나다 ②일어서다',
    circumstance: '①상황 ②환경',
    constrained: '①강요당한 ②부자연스러운',
    convention: '①협약 ②대회',
    era: '①시대 ②시절',
    financial: '①금융의 ②경제의',
    freedom: '①자유 ②석방',
    gender: '①성별 ②성',
    indeed: '①정말로 ②사실은',
    individuals: '개인들',
    liberal: '①진보적인 ②자유로운',
    qualify: '①자격을 갖추다 ②자격을 얻다',
    societies: '사회',
    timeless: '①시간을 초월한 ②무한한',
    accused: '①비난 받은 ②혐의를 받다',
    aides: '①도움이 되다 ②돕다',
    assistants: '①보조 ②조수',
    candidate: '①후보자 ②지원자',
    constant: '①일정한 ②지속적인',
    criticism: '①비판 ②비난',
    defeat: '①패배시키다 ②이기다',
    destructive: '①파괴적인 ②해로운',
    esteem: '①존중하다 ②평가하다',
    exaggerated: '①과장된 ②과대한',
    individuals: '개인들',
    narcissists: '자기 도취자',
    optimistic: '①낙관적인 ②긍정적인',
    politicians: '정치가',
    probable: '①가능성 ②그럴듯한',
    rationalize: '①합리화하다 ②유리화하다',
    revolves: '①순환하다 ②맴돌다',
    seriousness: '①중대함 ②진지함',
    spotlight: '스포트라이트',
    territory: '①영토 ②영역',
    trait: '①특징 ②특성',
    unnaturally: '부자연스럽게',
    accountable: '①책임이 있는 ②설명할 수 있는',
    alienation: '①소외 ②양도',
    anti: '①반대 ②반',
    anxiety: '①불안 ②걱정',
    boardrooms: '①이사회 회의실 ②매매소',
    bureaucracies: '①관료제 ②관료',
    capacity: '①능력 ②용량',
    corporations: '①기업 ②회사',
    deficit: '①적자 ②결손',
    determine: '①결정하다 ②밝히다',
    economic: '①경제의 ②경기의',
    eroding: '①침식하다 ②부식하다',
    fates: '①운명이다 ②운명',
    globalization: '①세계화 ②국제화',
    globalizers: '①세계화하다 ②전 세계에 퍼뜨리다',
    loyalties: '①성실 ②충성',
    oppose: '①반대하다 ②대항하다',
    remote: '①원격의 ②외딴',
    reserve: '①보유하다 ②보호지역',
    sovereign: '①주권자 ②주권의',
    transnational: '①다국적 기업의 ②다국적의',
    unleashing: '①놓아주다 ②ㅇㅇ의 속박을 풀다',
    adjusted: '①조정되다 ②적응하다',
    casual: '편한',
    clinic: '①병원 ②클리닉',
    comparison: '비교',
    considerable: '①상당한 ②꽤',
    devastated: '①큰 타격을 받은 ②황폐한',
    emotionally: '감정적으로',
    eventually: '①결국 ②마침내',
    fitted: '①장비가 갖추어진 ②꼭 맞는',
    outlook: '①전망 ②경치',
    pirate: '①해적 ②불법 복제',
    prosthesis: '①보철 ②인공물',
    thrill: '①스릴 ②흥분',
    definition: '①정의 ②개념',
    exhausted: '지친',
    functioning: '①기능 ②의식',
    intake: '①섭취 ②흡입',
    psychological: '①심리학의 ②정신의',
    accessible: '접근할 수 있는',
    alternatives: '①양자택일 ②한쪽',
    anti: '①반대 ②반',
    basis: '①기초 ②근거',
    biomechanical: '신체 역학의',
    broader: '①폭이 넓은 ②광대한',
    cellular: '①세포의 ②휴대전화',
    comprises: '①ㅇㅇ로 이뤄지다 ②구성하다',
    context: '①문맥 ②상황',
    diet: '식단',
    discourse: '①담론 ②담화',
    enhance: '①향상하다 ②강화하다',
    era: '①시대 ②시절',
    focuses: '①초점에 모이다 ②주의를 집중하다',
    guaranteed: '①보장하다 ②보증',
    healing: '①치유 ②치료',
    individual: '개인의',
    industry: '①산업 ②업계',
    insights: '①통찰 ②명찰',
    interactions: '①상호 작용 ②관련',
    longevity: '①장수 ②수명',
    medicinal: '①약효가 있는 ②약의',
    nutritional: '①영양의 ②영양상의',
    observation: '①관찰 ②관측',
    processes: '①처리하다 ②과정',
    promotes: '①홍보하다 ②승진시키다',
    supplements: '①추가 ②보각',
    associated: '①연관된 ②관계가 있는',
    cholera: '콜레라',
    epidemic: '①유행 ②유행병',
    fermented: '발효된',
    flawed: '흠이 있는',
    harsh: '①가혹한 ②거친',
    hindered: '①방해하다 ②막다',
    hygiene: '①위생 ②건강법',
    longevity: '①장수 ②수명',
    orthodoxy: '①정통파적 신념 ②정교적 신앙',
    prominent: '①유명한 ②두드러진',
    ripe: '①잘 익은 ②때가 된',
    speculate: '①추측하다 ②분석하다',
    zoologist: '동물학자',
    academic: '①학업의 ②학문적인',
    application: '①적용 ②응용',
    applying: '①적용하다 ②지원하다',
    corporate: '①기업의 ②회사의',
    finalists: '①결승전 출전자 ②대학 졸업 시험 수험자',
    granted: '①부여하다 ②주다',
    industry: '①산업 ②업계',
    inform: '알리다',
    qualifications: '①자질 ②자격',
    reapply: '①다시 적용하다 ②다시 쓰다',
    regret: '①후회하다 ②유감',
    scholarship: '①장학금 ②학문',
    slot: '①시간대 ②자리',
    adjust: '①조정되다 ②적응하다',
    barely: '①거의 ㅇㅇ않다 ②겨우',
    breath: '①숨 ②호흡',
    buoyancy: '①부력 ②부양성',
    confining: '①국한 ②제한된',
    dash: '①돌진하다 ②찬물을 끼얹다',
    disorientingly: '①길을 잃게 하는 ②혼란스럽게 만드는',
    grin: '①웃다 ②웃음',
    invertebrate: '①무척추동물 ②무척추동물의',
    lighted: '①빛 ②햇빛',
    proceed: '①나아가다 ②전진하다',
    refocus: '①다시 초점을 맞추다 ②중점을 바꾸다',
    signaled: '①신호 ②계기',
    uneasiness: '①불안 ②걱정',
    content: '①콘텐츠 ②내용',
    distracted: '①주의를 빼앗다 ②관심이 멀어지다',
    ensuring: '①확실하게 하다 ②확보하다',
    forgotten: '잊혀진',
    guarantee: '①보장하다 ②보증',
    internalised: '①내면화하다 ②자기 것으로 하다',
    intranet: '①인트라넷 ②내부 전산망',
    iuvant: '이반',
    multichannel: '①다중 통화의 ②다중 채널의',
    neglected: '①무시 ②방치하다',
    pondered: '①잘 생각하다 ②숙고하다',
    reception: '①수신 ②리셉션',
    redundant: '①여분의 ②장황한',
    relevant: '①관련있는 ②적절한',
    selection: '①선택 ②선발',
    automatic: '①자동의 ②자연적으로',
    claimed: '①주장하다 ②말하다',
    cooperation: '협력',
    dominated: '①지배하다 ②우뚝 솟다',
    enthusiastic: '①열정적인 ②열렬한',
    fastball: '①속구 ②패스트볼',
    foundation: '①재단 ②기반',
    individual: '개인의',
    intimidated: '①무서워하는 ②벌벌 떠는',
    intuitively: '직관적으로',
    league: '①리그 ②연맹',
    opposing: '①적대하는 ②정반대의',
    recognition: '①인식 ②인정',
    unstoppable: '①막을 수 없는 ②이길 수 없는',
    concierge: '①수위 ②관리인',
    conflict: '①갈등 ②분쟁',
    consumer: '①소비자 ②고객',
    employees: '직원들',
    ensure: '①ㅇㅇ하기 위해 ②보장하다',
    firms: '회사',
    fitness: '①건강 ②운동',
    interactions: '①상호 작용 ②관련',
    nondrinking: '①금주 ②술 끊기',
    nonsmokers: '비흡연자의 권리',
    patrons: '①단골 ②후원자',
    purchase: '①구매하다 ②구입하다',
    reunion: '①상봉 ②재회',
    satisfaction: '①만족 ②충족',
    significantly: '①크게 ②현저히',
    smokers: '①담배를 피우는 사람 ②흡연차',
    veterans: '①고참병 ②노련가',
    basically: '기본적으로',
    coaches: '①코치 ②감독',
    decades: '①십년간 ②수십년',
    define: '①정의하다 ②말한다',
    drumming: '①북을 치는 것 ②둥둥 울리는 소리',
    enhance: '①향상하다 ②강화하다',
    ensure: '①ㅇㅇ하기 위해 ②보장하다',
    foremost: '①최우선 ②가장',
    indeed: '①정말로 ②사실은',
    technique: '①기법 ②기술',
    token: '①토큰 ②표시',
    absorb: '①흡수하다 ②열중하다',
    alga: '①해조 ②말',
    biological: '①생물학의 ②생물학적 약제',
    coalburning: '석탄태움',
    consisting: '①이루어지다 ②구성되다',
    continually: '①계속해서 ②지속적으로',
    crusty: '①외각질의 ②무뚝뚝한',
    dioxide: '이산화물',
    excessive: '①과도한 ②지나친',
    existed: '①존재하다 ②있다',
    fungus: '①균 ②곰팡이',
    indicators: '①지표 ②지수',
    industrial: '①산업의 ②공업의',
    interdependent: '상호 의존의',
    lichen: '①이끼 ②지의의 식물',
    northwest: '①북서 ②노스웨스트',
    nourishment: '①음식물 ②영양',
    organism: '①생물 ②유기체',
    originates: '①시작하다 ②일으키다',
    pollutant: '①오염 물질 ②오염원',
    polluting: '①더럽히다 ②타락시키다',
    presence: '①존재 ②영향력',
    sicken: '①구역질나게 하다 ②못 쓰게 되다',
    specific: '①특정한 ②구체적인',
    sulfur: '유황의',
    varieties: '①다양성 ②변화',
    biodiversity: '생물의 다양성',
    destructive: '①파괴적인 ②해로운',
    diverse: '①다양한 ②여러 가지의',
    ecological: '①생태학적 ②환경 친화적인',
    economy: '①경제 ②경기',
    ecotourism: '환경관광',
    forested: '①숲 ②산림',
    frequent: '①자주 ②잦은',
    hardwoods: '①경재 ②경재의',
    harvested: '①수확 ②추수',
    hurricanes: '①허리케인 ②폭풍',
    lagoons: '뉴칼레도니섬 석호',
    landmass: '①대륙 ②광대한 육지',
    lowland: '①저지 ②저지의',
    mahogany: '①마호가니 ②마호가니색',
    reef: '①산호초 ②암초',
    subtropical: '①아열대의 ②아열대성의',
    swampy: '①습지가 많은 ②습지의',
    accounted: '①기술 ②변명',
    enrolled: '①등록하다 ②기록하다',
    enrollment: '①등록 ②입학',
    ethnic: '①민족의 ②혈통의',
    increase: '①증가하다 ②늘리다',
    multi: '①다중 ②다',
    terms: '①용어 ②기간',
    charge: '①혐의 ②충전',
    county: '①군 ②주',
    curator: '①큐레이터 ②전시기획자',
    guidelines: '①지침 ②가이드라인',
    participating: '참가적의',
    reception: '①수신 ②리셉션',
    register: '①등록하다 ②기록하다',
    abnormal: '①비정상적인 ②이상한',
    aeds: '①에이즈 ②지원',
    analysis: '①분석 ②해석',
    analyze: '①분석하다 ②조사하다',
    analyzing: '①분석하다 ②분석하여 조사하다',
    arrest: '①체포하다 ②구속하다',
    automated: '①자동화된 ②자동의',
    cardiac: '①심장의 ②심장병 환자',
    charge: '①혐의 ②충전',
    compression: '①압축 ②응축',
    critical: '①비판적인 ②중요한',
    defibrillators: '①세동 제거기 ②제세동기',
    detect: '①찾아내다 ②감지하다',
    electrical: '①전기의 ②전자의',
    external: '①외부의 ②대외적인',
    instruct: '①지시하다 ②교육하다',
    restore: '①복원하다 ②회복하다',
    victim: '①피해자 ②희생자',
    vocal: '①가창의 ②목소리의',
    acquaintance: '①아는 사람 ②인물',
    adapting: '①개조된 ②개작된',
    assume: '①가정하다 ②생각하다',
    assumption: '①가정 ②추측',
    attempting: '①시도하다 ②노력',
    conform: '①순응하다 ②따르다',
    cordiality: '①진심 ②충정',
    encounter: '①만나다 ②마주치다',
    impacting: '①충돌 ②영향',
    initiate: '시작하다',
    intentions: '좋은 의도',
    perspective: '①관점 ②시각',
    advise: '①조언하다 ②권하다',
    akin: '①비슷한 ②같이',
    clients: '고객',
    desire: '①욕망 ②싶다',
    developments: '①발달 ②발달한 상태',
    fertile: '①비옥한 ②가임의',
    fitted: '①장비가 갖추어진 ②꼭 맞는',
    haphazardly: '①계획 없이 ②엉터리로',
    imported: '①중요하다 ②수입하다',
    mismatches: '①부적당하게 짝지우다 ②부적당한 짝',
    rug: '①양탄자 ②깔개',
    selected: '①선택된 ②선발된',
    slope: '①경사 ②스키장',
    tract: '①관 ②지역',
    tuxedo: '턱시도',
    advantage: '①이점 ②우위',
    basis: '①기초 ②근거',
    capable: '①가능성있는 ②능력있는',
    collective: '①집단적인 ②공동의',
    compelling: '억지로 ㅇㅇ하게하다',
    competitiveness: '①경쟁력 ②장점',
    debilitating: '쇠약하게 만드는',
    employees: '직원들',
    fluid: '①유동성의 ②액체',
    halving: '①반분하다 ②반감하다',
    horsepower: '①마력 ②달성 능력',
    humanitarian: '①인도주의적인 ②인도주의자',
    incorporate: '①포함하다 ②결합하다',
    individual: '개인의',
    integrating: '①통합된 ②종합',
    intellectual: '①지적인 ②지식인',
    intelligence: '①지능 ②정보',
    laboratory: '①연구실 ②실험실',
    mobilization: '①동원 ②유통',
    mobilizing: '①동원되다 ②전시 동원하다',
    policy: '①정책 ②제도',
    radical: '①급진적인 ②과격한',
    sedentary: '①앉아서 하는 ②앉아 있는',
    setups: '①세트업 ②생각',
    strategic: '①전략적인 ②중요한',
    accessible: '접근할 수 있는',
    acquire: '①얻다 ②습득하다',
    attending: '①참석 ②다니는',
    conference: '①회견 ②회의',
    constructed: '①만들다 ②건설하다',
    dedicated: '①헌신적인 ②전용의',
    documentaries: '①문서의 ②기록물',
    expertise: '①전문적 기술 ②전문 기술',
    freak: '①열광자 ②별난',
    indeed: '①정말로 ②사실은',
    programmes: 'program',
    reconstruct: '①재구성 ②재건',
    wiped: '①닦다 ②없애다',
    conclude: '결론짓다',
    consensus: '①합의 ②의견',
    enthusiastically: '①열심히 ②열광하여',
    guilty: '①유죄의 ②죄책감',
    initially: '①처음에 ②당초에',
    interrogators: '①질문자 ②호출기',
    motivation: '①동기 부여 ②욕구',
    persuasive: '①설득력 있는 ②설득적인',
    political: '①정치의 ②정당의',
    shortcut: '①지름길 ②첩경',
    witnessed: '①증명하다 ②목격하다',
    advocate: '①옹호하다 ②주장하다',
    capacity: '①능력 ②용량',
    characterized: '①간주하다 ②특징을 나타내다',
    civil: '①시민의 ②민사의',
    claims: '①주장하다 ②말하다',
    colonial: '①식민지의 ②일제 강점기',
    colonies: '①식민단 ②식민지',
    conflict: '①갈등 ②분쟁',
    crucial: '①중요한 ②결정적인',
    dismissively: '①거만한 ②멸시하는',
    examining: '①검사하다 ②시험하다',
    excluded: '①제외하다 ②배제하다',
    export: '①수출 ②수출액',
    functionaries: '①직원 ②공무원',
    imperial: '①제국의 ②황제의',
    individuals: '개인들',
    latter: '①후자의 ②하반기의',
    marginal: '①가장자리의 ②경계의',
    mechanism: '①메커니즘 ②장치',
    membership: '회원',
    participating: '참가적의',
    participation: '①참여 ②참가',
    profit: '①이익 ②수익',
    settle: '①해결하다 ②정착하다',
    superfluous: '①여분의 ②불필요한',
    surplus: '①흑자 ②무역수지',
    affect: '①영향을 주다 ②작용하다',
    agricultural: '①농업의 ②농산의',
    algal: '①해조의 ②조류의',
    associated: '①연관된 ②관계가 있는',
    chemical: '①화학적인 ②화학물질',
    commercial: '①상업용의 ②상업적인',
    downstream: '①하류 부문의 ②흐름을 따른',
    ecology: '생태 환경',
    economic: '①경제의 ②경기의',
    elevated: '①높은 ②고상한',
    eroded: '①침식하다 ②부식하다',
    eventually: '①결국 ②마침내',
    fertilizers: '비료',
    fisheries: '①어업 ②수산 회사',
    groundwater: '①지하수 ②갱내수',
    impacts: '①충돌 ②영향',
    increase: '①증가하다 ②늘리다',
    inputs: '①입력 ②산업',
    killers: '①죽이는 사람 ②멎게 하는 것',
    nutrient: '영양',
    pesticides: '①농약 ②살충제',
    recreational: '①휴양의 ②오락의',
    regional: '①지역의 ②지방의',
    sediment: '①침전물 ②앙금',
    ultimately: '①마침내 ②결국',
    weed: '①잡초 ②제거하다',
    accomplish: '①성취하다 ②이루어 내다',
    emerged: '①떠오르다 ②드러나다',
    establishing: '①수립하다 ②제정하다',
    identify: '①확인하다 ②알아보다',
    identity: '①정체성 ②자신',
    indicated: '①나타내다 ②가리키다',
    insights: '①통찰 ②명찰',
    involved: '①관련된 ②관여하는',
    minimize: '①과소평가하다 ②줄이다',
    participant: '①참가자 ②참여자',
    rapport: '①관계 ②협조',
    revealing: '①드러내다 ②나타내다',
    simultaneously: '①동시에 ②일제히',
    sociological: '①사회 조직의 ②사회의',
    sociologists: '사회학자',
    strive: '①노력하다 ②애쓰다',
    altered: '①변하다 ②바뀌다',
    approved: '①승인된 ②통과된',
    checkered: '①바둑판무늬인 ②가지각색의',
    chronically: '만성적으로',
    commercial: '①상업용의 ②상업적인',
    composed: '①구성하다 ②작곡하다',
    coppicing: '잡목림을 이룬',
    degrading: '①품위를 떨어뜨리는 ②품격을 낮추는',
    erosion: '①침식 ②부식',
    existing: '①기존의 ②존재하는',
    favored: '①부탁 ②선호하다',
    habitat: '①서식지 ②생태',
    hence: '①그러므로 ②앞으로',
    inhibits: '①억제하다 ②금하다',
    litter: '①쓰레기 ②한배의 새끼',
    masked: '①마스크 ②가면',
    midlatitude: '중위도',
    mosaic: '①모자이크 ②모세의',
    northwest: '①북서 ②노스웨스트',
    plots: '①음모 ②줄거리',
    rainforest: '①열대 우림 ②레인포리스트',
    reforestation: '재식림',
    regeneration: '①갱생 ②재건',
    replacing: '①대신하다 ②바꾸다',
    replanted: '①옮겨 심다 ②재이식하다',
    saplings: '①어린 나무 ②젊은이',
    strategy: '전략',
    tropics: '①열대 지방의 ②열대성의',
    undergrowth: '①덤불 ②나무 그늘의 풀',
    utilizing: '①이용하다 ②활용하다',
    alternative: '①대안 ②대체',
    bias: '①편견 ②치우침',
    conscious: '①의식한 ②친화적',
    cumbersome: '①성가신 ②다루기 힘든',
    excludes: '①제외하다 ②배제하다',
    gender: '①성별 ②성',
    inclusive: '①일체를 포함한 ②포괄적인',
    interpersonal: '대인 관계의',
    masculine: '①남성의 ②남자다운',
    neutral: '①중립 ②중성',
    pronoun: '대명사',
    rephrase: '고쳐 말하다',
    sexist: '성 차별주의자',
    terms: '①용어 ②기간',
    associated: '①연관된 ②관계가 있는',
    belonging: '①속하다 ②ㅇㅇ의 것이다',
    consumption: '①소비 ②소비량',
    contribute: '①기여하다 ②공헌하다',
    desires: '①욕망을 가지다 ②바라다',
    differentiation: '①차이 ②분화',
    distant: '①먼 ②원격의',
    distinction: '①구별 ②차이',
    distinctive: '①독특한 ②특유의',
    fandom: '①팬 전체 ②팬 층',
    framework: '①근거 ②체제',
    fundamental: '①기본적인 ②근본적인',
    identification: '①표시 ②동정',
    identifying: '①확인하다 ②알아보다',
    inclusion: '①통합 ②포함',
    individuals: '개인들',
    mainstream: '①주류 ②대세',
    opposing: '①적대하는 ②정반대의',
    optimal: '①최선의 ②가장 바람직한',
    partially: '①부분적으로 ②일부',
    satisfy: '①만족시키다 ②충족시키다',
    selectively: '①선별하여 ②선별적으로',
    simultaneously: '①동시에 ②일제히',
    strive: '①노력하다 ②애쓰다',
    underdog: '①패배자 ②사회적 부정의 희생자',
    uniqueness: '①유례없는 일 ②독특함',
    accomplished: '①성취하다 ②이루어 내다',
    accomplishment: '①성취 ②업적',
    arbitrary: '①임의의 ②독단적인',
    chunking: '청킹',
    cognition: '①인지 ②인식',
    complex: '①복잡한 ②복합의',
    compositions: '①구성 ②작문',
    construct: '①만들다 ②건설하다',
    describing: '①묘사하다 ②말하다',
    encode: '①부호화하다 ②암호문으로 바꾸다',
    individual: '개인의',
    phrase: '①말 ②구절',
    recall: '①상기하다 ②기억하다',
    reel: '①비틀거리다 ②휘청거리다',
    rehearsal: '①예행 연습 ②리허설',
    replay: '①다시 하다 ②재연하다',
    restarting: '①재출발시키다 ②재시동',
    retreading: '다시 바닥을 붙이다',
    seemingly: '①겉보기에는 ②언뜻 보기에',
    sonata: '①소나타 ②주명곡',
    arise: '①발생하다 ②생기다',
    attack: '①공격하다 ②발작',
    basically: '기본적으로',
    cognitive: '①인식의 ②인지의',
    confirmation: '①확인 ②확증',
    confirmed: '①확인된 ②승인된',
    context: '①문맥 ②상황',
    correction: '①교정 ②수정',
    criticism: '①비판 ②비난',
    digesting: '①소화하다 ②먹다',
    disagreements: '①이견 ②불일치',
    doctrines: '①원칙 ②독트린',
    empirical: '①경험적인 ②경험의',
    endless: '①끝없는 ②무한한',
    exaggerates: '①과장해서 쓰다 ②과장해서 말하다',
    factual: '①사실에 입각한 ②사실의',
    furiously: '①극단적으로 ②미친 듯 날뛰며',
    hypotheses: '①가정하다 ②가설',
    interpret: '①해석하다 ②통역하다',
    lacks: '①부족 ②ㅇㅇ이 없다',
    mapping: '①지도 제작 ②사상',
    mechanism: '①메커니즘 ②장치',
    neglects: '①무시 ②경시',
    partial: '①부분적인 ②국소',
    practical: '①실용적인 ②실제적인',
    primarily: '①주로 ②우선',
    pseudoscience: '의사 과학',
    pseudoscientist: '가짜 과학자',
    rejects: '①거절하다 ②버리다',
    sect: '①종파 ②파벌',
    splitting: '①파편 ②쪼개지는',
    untestable: '유언할 능력이 없는',
    afterward: '①그후 ②곧 이어',
    batting: '①타격 ②이불 솜',
    burst: '①터지다 ②터뜨리다',
    deserved: '①받을 만하다 ②가치가 있다',
    dirt: '①흙 ②먼지',
    fence: '①울타리 ②펜싱',
    playoff: '①재시합 ②연장전',
    resumed: '①다시 시작하다 ②다시 차지하다',
    rivals: '①경쟁하는 ②경쟁자',
    shedding: '①흘리기 ②빈 껍질',
    shortstop: '①유격수 ②다른 사람에게 돌리기 전에 덜다',
    smashed: '①치다 ②강타하다',
    softball: '①소프트볼 ②그 공',
    sportsmanship: '①스포츠맨 정신 ②스포츠 정신',
    sprinted: '전속력으로 달리다',
    substitute: '①대체하다 ②대신',
    teammates: '①팀의 한 사람 ②단원',
    thrilled: '①스릴 ②흥분',
    umpire: '①심판 ②중재하다',
    uninjured: '①상해를 입지 않은 ②무사한',
    accommodate: '①수용하다 ②맞추다',
    additional: '①추가의 ②더',
    bookshelves: '책장',
    improvements: '①개선 ②향상',
    maintenance: '①유지 ②관리',
    minimized: '①ㅇㅇ의 양을 최소 한도로 하다 ②최소 한도로 평가하다',
    absolutely: '①절대적으로 ②완전히',
    absorbed: '①흡수하다 ②열중하다',
    anticipation: '①기대 ②예상',
    anxiety: '①불안 ②걱정',
    bowed: '①활 ②인사하다',
    goosebumps: '소름',
    hostess: '①호스티스 ②여주인',
    joyful: '즐거운',
    jury: '①배심 ②심사위원',
    practically: '①사실상 ②실제로',
    radiated: '①방사상으로 퍼져 나가다 ②빛을 발하다',
    spotlight: '스포트라이트',
    squeezed: '수분을 짜다',
    trembling: '①떨림 ②전율하는',
    warmth: '①따뜻함 ②온기',
    approach: '①접근하다 ②접근법',
    campus: '①캠퍼스 ②대학',
    convinced: '①확신하는 ②설득했다',
    corridor: '복도',
    existing: '①기존의 ②존재하는',
    isolate: '①분리하다 ②고립시키다',
    propped: '①앞다리를 버티어 딱 서다 ②받치다',
    residence: '①주택 ②주거',
    uncertain: '①불확실한 ②불투명한',
    absurd: '①말도 안되는 ②터무니없는',
    acceptance: '받아들임',
    accomplishment: '①성취 ②업적',
    affiliations: '①관계 ②소속',
    allies: '①ally의 복수형 ②연합국',
    basis: '①기초 ②근거',
    belonging: '①속하다 ②ㅇㅇ의 것이다',
    critical: '①비판적인 ②중요한',
    depend: '의존하다',
    essence: '①본질 ②정수',
    ethnic: '①민족의 ②혈통의',
    forged: '①노 ②괴철로',
    freedom: '①자유 ②석방',
    identification: '①표시 ②동정',
    identities: '①동일함 ②본인임',
    identity: '①정체성 ②자신',
    indeed: '①정말로 ②사실은',
    liable: '①책임 있는 ②ㅇㅇ해야 할',
    racial: '①인종의 ②민족의',
    satisfying: '①만족시키다 ②충족시키다',
    secure: '①확보하다 ②안전한',
    threatened: '①위협당한 ②협박당한',
    unconditional: '①무조건의 ②무제한의',
    aesthetic: '미학의',
    analytics: '①분석론 ②해석학',
    capable: '①가능성있는 ②능력있는',
    capacity: '①능력 ②용량',
    contextually: '맥락과 관련하여',
    dimensions: '①크기',
    domains: '①분야 ②영토',
    dominate: '①지배하다 ②장악하다',
    economic: '①경제의 ②경기의',
    efficient: '효율적인',
    embedding: '①내장된 ②뿌리박힌',
    humanities: '①인간성 ②인류',
    identify: '①확인하다 ②알아보다',
    narratives: '①설명적인 ②이야기',
    organizational: '①조직적 ②기관의',
    qualitatively: '질적으로',
    quantitatively: '양적으로',
    relevant: '①관련있는 ②적절한',
    significant: '①중요한 ②상당한',
    societal: '①사회의 ②사회 활동의',
    stakeholders: '건 돈을 보관하는 사람',
    sustainable: '지속 가능한',
    transformation: '①전환 ②변화',
    ultimately: '①마침내 ②결국',
    aware: '①알고 있는 ②인식하는',
    ceased: '①그만두다 ②종지',
    clarified: '①정화된 ②맑아진',
    commas: '①콤마 ②콤마',
    considerably: '①많이 ②상당히',
    construct: '①만들다 ②건설하다',
    diminishing: '점감하는',
    doubtless: '①틀림없이 ②의심할 여지 없이',
    established: '①설립하다 ②세우다',
    firmly: '①확고하게 ②강하게',
    interrupts: '①중단하다 ②개입 중단',
    nonessential: '①비본질적인 ②불필요한',
    notation: '①표기법 ②악보법',
    omitted: '①빠뜨리다 ②안하고 넘어가다',
    predecessors: '①전임자 ②전에 있던 것',
    punctuation: '①구두점 ②구두법',
    tendency: '①경향 ②추세',
    achieving: '①성과를 올리다 ②성취하다',
    application: '①적용 ②응용',
    bubble: '①거품 ②기포',
    carving: '①조각 ②조각물',
    complex: '①복잡한 ②복합의',
    confronted: '①직면하다 ②앞길을 가로막다',
    converted: '①전환하다 ②바꾸다',
    decay: '①부패 ②붕괴하다',
    decline: '①감소하다 ②거절하다',
    demarcated: '①ㅇㅇ의 경계선을 긋다 ②선으로 구획하다',
    demarcation: '①구분 ②경계 획정',
    efficient: '효율적인',
    entertainment: '①오락 ②연예',
    entirety: '①완전한 상태 ②전부',
    gleaming: '①희미하게 빛나다 ②비치다',
    hostile: '①적대적인 ②호전적인',
    insolvable: '①녹지 않는 ②해결할 수 없는',
    neglect: '①무시 ②방치하다',
    renewal: '①갱신 ②재개',
    scarce: '①부족한 ②희귀한',
    securing: '①안전한 ②안전하게 보관된',
    seemingly: '①겉보기에는 ②언뜻 보기에',
    simulacrum: '①상 ②닮은 모습',
    strategy: '전략',
    tempting: '유혹하는',
    tourism: '①관광 ②여행',
    academy: '①아카데미 ②학술원',
    accumulated: '①쌓아 올리다 ②쌓이다',
    acquired: '①얻다 ②습득하다',
    adapted: '①개조된 ②적합한',
    administrator: '①행정관 ②관리자',
    enrolled: '①등록하다 ②기록하다',
    immense: '①굉장한 ②막대한',
    inclinations: '①성향 ②의향',
    proceeded: '①나아가다 ②전진하다',
    prominent: '①유명한 ②두드러진',
    remarried: '재혼시키다',
    researches: '①조사하다 ②조사하다',
    additives: '①부가적인 ②첨가물',
    antibiotics: '①항생제 ②항균',
    evaluation: '①평가 ②분석',
    gender: '①성별 ②성',
    inclined: '①마음이 내키는 ②경향이 있는',
    percentage: '①포인트 ②비율',
    pesticides: '①농약 ②살충제',
    preservatives: '①보존하는 ②보존력이 있는',
    sorted: '①분류하다 ②정렬하다',
    wary: '①조심하는 ②신중한',
    aisle: '①통로 ②매장',
    annual: '①연간의 ②연례의',
    arrange: '①배치하다 ②준비하다',
    brief: '①보고서 ②짧은',
    luminaria: '루미나리아',
    registration: '①등록 ②접수',
    twinkling: '반짝반짝 빛나는',
    weighted: '①무게를 지운 ②기운',
    adjust: '①조정되다 ②적응하다',
    debit: '①차변 ②차변 기입',
    hire: '①고용하다 ②채용하다',
    inserted: '①삽입하다 ②넣다',
    keypad: '①키패드 ②리모컨',
    unlock: '①열다 ②잠기지 않은',
    wheel: '①바퀴 ②자동차',
    achieving: '①성과를 올리다 ②성취하다',
    admit: '①인정하다 ②시인하다',
    appointment: '①임명 ②약속',
    commit: '①저지르다 ②범하다',
    deliberately: '①의도적으로 ②고의로',
    economy: '①경제 ②경기',
    efficiency: '①효율 ②능률',
    efficient: '효율적인',
    forcing: '①강제 ②폭행',
    generalisations: '①an idea or conclusion having general application ②the process of formulating by abstracting common properties of instances',
    intends: '①예정하다 ②향하게 하다',
    journalist: '①기자 ②언론인',
    obstacle: '①장애 ②방해',
    ploy: '①상대의 콧대를 꺾는 책략 ②횡대에서 종대로 한다',
    politician: '정치가',
    precisely: '①정확히 ②정밀하게',
    sector: '①부문 ②분야',
    vague: '①모호한 ②애매한',
    veil: '①베일 ②가리다',
    blend: '①혼합 ②혼합물',
    continuum: '①연속 ②연속체',
    diluted: '①희박해지다 ②묽어지다',
    establishes: '①수립하다 ②제정하다',
    gradation: '①단계 ②그러데이션',
    identity: '①정체성 ②자신',
    mixes: '①섞다 ②혼합하다',
    proportional: '①균형 잡힌 ②비례하는',
    retains: '①유지하다 ②보유하다',
    aura: '①아우라 ②전조',
    ballgame: '①구기 ②야구',
    broadly: '①광범위하게 ②거리낌없는',
    checkout: '①보다 ②확인하다',
    definite: '①명확한 ②분명한',
    emotional: '감정적인',
    grocery: '①식료품 ②잡화류',
    hint: '①시사 ②힌트',
    presence: '①존재 ②영향력',
    psychological: '①심리학의 ②정신의',
    aimless: '①목적 없는 ②목적이 없는',
    continually: '①계속해서 ②지속적으로',
    function: '①기능 ②역할',
    independently: '①독립적으로 ②자유롭게',
    involve: '①관련되다 ②참여하다',
    paradoxically: '①역설적으로 ②역설적으로 말하면',
    practical: '①실용적인 ②실제적인',
    sensations: '①감각 ②센세이션',
    stocked: '①주식 ②증권',
    surroundings: '①주위의 ②주변의',
    unfamiliar: '①낯선 ②익숙지 않은',
    barely: '①거의 ㅇㅇ않다 ②겨우',
    deadline: '①마감일 ②데드라인',
    fellowship: '①단체 ②동료 의식',
    fondness: '①자애 ②기호',
    hardship: '①고난 ②어려움',
    recount: '①이야기하다 ②묘사하다',
    attack: '①공격하다 ②발작',
    confuses: '①불명확하게 하다 ②혼란시키다',
    existence: '①존재 ②현존',
    herbivore: '①초식 동물 ②유제류',
    herds: '①무리 ②양치기',
    lack: '①부족 ②ㅇㅇ이 없다',
    pursuers: '추적자들',
    territory: '①영토 ②영역',
    trail: '①둘레길 ②등산로',
    travelling: '①이동 ②이동하는',
    tum: '①둥 ②뎅',
    undisturbed: '방해받지 않은',
    advent: '①출현 ②도래',
    burgeoning: '①급증하는 ②급성장 하는',
    consumer: '①소비자 ②고객',
    critical: '①비판적인 ②중요한',
    distribution: '①분포 ②분배',
    economic: '①경제의 ②경기의',
    economies: '①할인 가격으로 ②경제적인',
    increase: '①증가하다 ②늘리다',
    industrial: '①산업의 ②공업의',
    labor: '①노동 ②근로',
    manual: '①안내책자 ②수동의',
    manufacturing: '①제조 ②생산',
    packaging: '①포장 ②짐꾸리기',
    production: '①생산 ②제작',
    purchase: '①구매하다 ②구입하다',
    complex: '①복잡한 ②복합의',
    deficiencies: '①부족 ②부족액',
    deficiency: '①부족 ②결함',
    explanation: '①설명 ②해명',
    imposed: '①지우다 ②강요하다',
    interaction: '①상호 작용 ②관계',
    lack: '①부족 ②ㅇㅇ이 없다',
    limited: '①한정된 ②제한을 받은',
    logical: '①논리적인 ②타당한',
    restrictions: '①제한 ②제한하는 것',
    afford: '①여유가 있다 ②할 수 있다',
    alternatives: '①양자택일 ②한쪽',
    cash: '①현금 ②돈',
    charge: '①혐의 ②충전',
    consolidation: '①합병 ②통합',
    corporate: '①기업의 ②회사의',
    corporations: '①기업 ②회사',
    diversity: '①다양성 ②상이',
    economic: '①경제의 ②경기의',
    fees: '①요금 ②축의금',
    hefty: '①크고 튼튼한 ②커서 움직이기 어려운',
    increase: '①증가하다 ②늘리다',
    individual: '개인의',
    interdependence: '상호 의존',
    maintain: '①유지하다 ②계속하다',
    providers: '①제공자 ②사업자',
    purchases: '①구매하다 ②구입하다',
    suppliers: '①공급하는 사람 ②원료 공급국',
    thriving: '①번영하는 ②번성하는',
    transaction: '①거래 ②트랜잭션',
    uniqueness: '①유례없는 일 ②독특함',
    applications: '①적용 ②응용',
    atmospheric: '①대기의 ②대기로 이루어진',
    components: '①성분 ②구성 요소',
    compressed: '①압축하다 ②습포',
    cork: '①코르크 ②마개',
    electronic: '①전자기기 ②전자의',
    gaseous: '①가스의 ②기체의',
    industry: '①산업 ②업계',
    nitrogen: '질소',
    oxidation: '산화',
    production: '①생산 ②제작',
    pumped: '흥분한',
    reactive: '①반응이 빠른 ②반작용을 나타내는',
    rotting: '①젠장 ②제기랄',
    storage: '①저장 ②보관',
    undesired: '바라지 않은',
    capacities: '①수용력 한도까지의 ②최대한의',
    capacity: '①능력 ②용량',
    circulate: '①돌다 ②유통되다',
    cooperative: '협력적인',
    gossip: '①소문 ②험담',
    maintenance: '①유지 ②관리',
    optimal: '①최선의 ②가장 바람직한',
    primate: '①영장류 ②수석 주교',
    sustain: '①지속하다 ②부상을 입다',
    adaptive: '①적응할 수 있는 ②적응하는',
    alternatives: '①양자택일 ②한쪽',
    approach: '①접근하다 ②접근법',
    assess: '①평가 ②결정',
    assume: '①가정하다 ②생각하다',
    conditional: '조건부의',
    confirming: '①확인된 ②승인된',
    contextual: '①문맥상의 ②전후 관계에서 본',
    depend: '의존하다',
    enable: '가능하게하다',
    examine: '①조사하다 ②검토하다',
    favored: '①부탁 ②선호하다',
    inactions: '①행동하지 않음 ②부작위',
    initial: '①처음의 ②머릿글자로 된',
    nontarget: '①대상 외의 ②목표 외의',
    outcomes: '①결과 ②성과',
    outset: '①착수 ②시작',
    policies: '①방침 ②정책',
    policy: '①정책 ②제도',
    uncertainty: '불확실성',
    yield: '①수확 ②항복',
    adopt: '①채택하다 ②입양하다',
    affect: '①영향을 주다 ②작용하다',
    assumed: '①가장한 ②꾸민',
    authorities: '①권위 ②권한',
    authority: '①당국 ②권한',
    beneficial: '①이로운 ②유익한',
    compassionately: '①연민으로 ②동정하여',
    conduct: '①실시하다 ②수행하다',
    depend: '의존하다',
    designate: '①지정하다 ②지명하다',
    dilemma: '①딜레마 ②어려운 문제',
    empowered: '권한을 주다',
    engaging: '①애교있는 ②매력 있는',
    facilitate: '①위하다 ②촉진하다',
    formal: '①공식적인 ②정식의',
    function: '①기능 ②역할',
    governing: '①통치하다 ②지배하다',
    individual: '개인의',
    informal: '①비공식 ②비형식',
    inherent: '①내재된 ②고유의',
    legitimacy: '①적법 ②정통',
    motives: '①동기 ②의도',
    precursors: '①선구자 ②전조',
    promote: '①홍보하다 ②승진시키다',
    regulatory: '①규제의 ②조정력을 가진',
    term: '①용어 ②기간',
    voluntarily: '①자발적으로 ②자주 적으로',
    beg: '①구걸하다 ②부탁하다',
    needless: '①불필요한 ②쓸데없는',
    plead: '①애원하다 ②호소하다',
    reserves: '①보유하다 ②보호지역',
    spectacular: '①장관의 ②화려한',
    stake: '지분',
    analyst: '①분석가 ②애널리스트',
    circulated: '①돌다 ②이동하다',
    condoned: '①용서하다 ②눈감아주다',
    cooperation: '협력',
    corporation: '①기업 ②회사',
    crashed: '①충돌하다 ②추락하다',
    crippling: '①지체장애 ②손상된',
    departments: '①부',
    expertise: '①전문적 기술 ②전문 기술',
    firm: '①단단한 ②회사',
    hubs: '①중심적인 ②허브',
    inappropriate: '①부적당한 ②알맞지 않은',
    intranet: '①인트라넷 ②내부 전산망',
    justify: '①정당화하다 ②그럴만한',
    overloaded: '①초과 적재 ②과부하',
    servers: '①봉사자 ②서브하는 사람',
    singular: '①단수의 ②독특한',
    specific: '①특정한 ②구체적인',
    temporarily: '①일시적으로 ②임시로',
    thematically: '주제별로',
    visually: '①시각적으로 ②시각에 관하여',
    applications: '①적용 ②응용',
    broadly: '①광범위하게 ②거리낌없는',
    bucket: '①양동이 ②버킷',
    confused: '①혼란한 ②헛갈리는',
    financial: '①금융의 ②경제의',
    handed: '①손잡이가 있는 ②손이 있는',
    joyfully: '①기뻐서 ②기쁜 듯이',
    stern: '①엄중한 ②강경한',
    adaptation: '①적응 ②각색',
    affect: '①영향을 주다 ②작용하다',
    contrary: '①반대의 ②정반대의',
    developments: '①발달 ②발달한 상태',
    disruptions: '①붕괴 ②파열',
    ease: '①완화하다 ②덜어주다',
    economic: '①경제의 ②경기의',
    economy: '①경제 ②경기',
    endure: '①견디다 ②지속하다',
    globalization: '①세계화 ②국제화',
    globalized: '①세계화하다 ②전 세계에 퍼뜨리다',
    inclusion: '①통합 ②포함',
    inequalities: '①불평등 ②불균형',
    innovation: '①혁신 ②획기적인',
    latter: '①후자의 ②하반기의',
    policies: '①방침 ②정책',
    processes: '①처리하다 ②과정',
    societies: '사회',
    socio: '사회의',
    steer: '①조종하다 ②돌리다',
    technological: '기술적인',
    transformations: '①전환 ②변화',
    transition: '①변화 ②전환',
    uncertainty: '불확실성',
    unfold: '①펴다 ②펼치다',
    additional: '①추가의 ②더',
    combining: '①결합시키다 ②합치다',
    competitors: '①경쟁자 ②선수',
    copied: '①대처하다 ②맞서다',
    economies: '①할인 가격으로 ②경제적인',
    firm: '①단단한 ②회사',
    harmed: '①해치다 ②손상하다',
    imitate: '①모방하다 ②흉내내다',
    imitation: '①모방 ②모조품',
    industrial: '①산업의 ②공업의',
    industries: '①산업 ②경영자',
    industry: '①산업 ②업계',
    innovate: '①혁신하다 ②쇄신하다',
    innovation: '①혁신 ②획기적인',
    isolated: '①고립된 ②절연된',
    localization: '①지방화 ②국한',
    modification: '①수정 ②변경',
    modifying: '①변경하다 ②변형하다',
    scattered: '①뿌려진 ②흩어져 있는',
    badge: '①배지 ②증표',
    belonging: '①속하다 ②ㅇㅇ의 것이다',
    conflict: '①갈등 ②분쟁',
    divisive: '①구별하는 ②불화를 일으키는',
    dumpster: '①금속제 대형 쓰레기통 ②대형 쓰레기 상자',
    enact: '①제정하다 ②입법하다',
    humorous: '①우스운 ②유머러스한',
    incidents: '①사건 ②부수적인 것',
    indicate: '①나타내다 ②가리키다',
    informal: '①비공식 ②비형식',
    initially: '①처음에 ②당초에',
    laughable: '①우스운 ②우스꽝스러운',
    membership: '회원',
    multiple: '다수의',
    organizational: '①조직적 ②기관의',
    perspective: '①관점 ②시각',
    recounting: '①이야기하다 ②묘사하다',
    reframes: '①다시 구성하다 ②틀을 다시 붙이다',
    reinforces: '①보강하다 ②늘리다',
    spark: '①촉발시키다 ②스파크',
    subservient: '①보조적인 ②부차적인',
    unifying: '①통합하다 ②하나로 하다',
    attitude: '①태도 ②자세',
    bestseller: '①베스트셀러 ②잘 팔리는 것',
    centre: '중심',
    conservative: '①보수적인 ②보수주의자',
    desperately: '①절실하게 ②필사적으로',
    experiential: '①경험에 의한 ②경험상의',
    extended: '①확장하다 ②연장하다',
    interactive: '①대화식의 ②쌍방향의',
    league: '①리그 ②연맹',
    medieval: '중세의',
    statistic: '①통계량 ②통계',
    ultimate: '①궁극적인 ②최종의',
    additionally: '①게다가 ②또한',
    congress: '①의회 ②회의',
    declined: '①감소하다 ②거절하다',
    deficit: '①적자 ②결손',
    economy: '①경제 ②경기',
    needy: '①가난한 ②빈곤한',
    percentage: '①포인트 ②비율',
    priorities: '①먼저임 ②우선하는 것',
    prioritize: '①우선시하다 ②우선순위',
    priority: '①우선 ②중요',
    securing: '①안전한 ②안전하게 보관된',
    security: '①보안 ②안보',
    strengthening: '①강화하다 ②강하다',
    abusua: '①학대하다 ②남용하다',
    ancestors: '①조상 ②선조',
    asamando: '①한 개인으로서 ②하나의 남자로서',
    burial: '①매장 ②묘소',
    ceremonies: '①의식 ②예의',
    culminates: '①끝나게 하다 ②완결시키다',
    deceased: '①사망한 ②죽은',
    distant: '①먼 ②원격의',
    distributed: '①분포된 ②광범위한',
    funeral: '①장례의 ②상례',
    maternal: '①어머니의 ②어머니다운',
    matriclan: '①귀족의 ②귀족',
    memorialize: '①기념하다 ②청원서를 제출하다',
    mortuary: '①영안실 ②매장의',
    mourners: '회개자석',
    notify: '①통보하다 ②알리다',
    biologist: '생물학자',
    constant: '①일정한 ②지속적인',
    discards: '①가진 패를 버리다 ②버리다',
    immense: '①굉장한 ②막대한',
    incoming: '①들어오는 ②후임의',
    laureate: '①수상자 ②월계관을 쓴',
    molecular: '분자의',
    narrative: '①설명적인 ②이야기',
    organs: '①오르간 ②기관',
    processes: '①처리하다 ②과정',
    reveals: '①드러내다 ②나타내다',
    sensory: '①감각의 ②지각의',
    sequence: '①서열 ②순서',
    temporal: '①시간의 ②관자놀이의',
    abound: '①풍부하다 ②많이 있다',
    anecdotes: '일화',
    claims: '①주장하다 ②말하다',
    cleanses: '①깨끗이 되다 ②세척하다',
    curse: '①저주 ②욕설',
    debating: '①토론 ②논의',
    educational: '교육의',
    entangled: '①걸려든 ②말려든',
    exaggeration: '①과장 ②과장법',
    grateful: '①감사하는 ②고마운',
    manipulate: '①조작하다 ②조종하다',
    megadosing: '①대량 투여 ②대량 투여하다',
    navigator: '①항해자 ②조종자',
    organic: '①유기적인 ②근본적인',
    preconceived: '①선입관 ②선입견',
    promoting: '①홍보하다 ②승진시키다',
    rare: '①희귀한 ②드문',
    seek: '①추구하다 ②찾다',
    vaccines: '①두묘 ②백신',
    valid: '①유효한 ②타당한',
    arthritic: '①관절염의 ②노화 의',
    biography: '①전기 ②자서전',
    cash: '①현금 ②돈',
    choppiness: '①파도가 일렁댐 ②고르지 못함',
    crookedly: '①구부러져서 ②부정하게',
    deathbed: '①죽음의 자리 ②임종',
    description: '①기술 ②설명',
    inability: '①할 수 없음 ②무능력',
    persistence: '①고집 ②지속',
    persuading: '①조르다 ②확신시키다',
    prolong: '①장기화하다 ②연장하다',
    remarked: '언급하다',
    summons: '①소환하다 ②불러내다',
    youthfulness: '①젊음 ②젊다는 것',
    buyers: '①구매자 ②바이어',
    comparison: '비교',
    considerable: '①상당한 ②꽤',
    consumer: '①소비자 ②고객',
    convenience: '①편의 ②편리',
    grocer: '식료 잡화점',
    purchasing: '①구매하다 ②구입하다',
    restrained: '①삼가는 ②자제된',
    secure: '①확보하다 ②안전한',
    trusted: '신뢰받고 있는',
    aggression: '①공격 ②공격성',
    assess: '①평가 ②결정',
    diverse: '①다양한 ②여러 가지의',
    dominated: '①지배하다 ②우뚝 솟다',
    fostered: '①육성하다 ②증진하다',
    indicated: '①나타내다 ②가리키다',
    lack: '①부족 ②ㅇㅇ이 없다',
    nonpatient: '①미불 ②미납',
    promoting: '①홍보하다 ②승진시키다',
    psychological: '①심리학의 ②정신의',
    questionnaire: '①설문지 ②질문서',
    ratings: '등급 매기기',
    reductions: '①축소 ②축도',
    restoration: '①복원 ②복구',
    restorative: '①강장제 ②복구의',
    significantly: '①크게 ②현저히',
    sustained: '①지속된 ②한결같은',
    unblighted: '①불이 밝혀져 있지 않은 ②점화되어 있지 않은',
    undistinguished: '차이점이 없는',
    vegetation: '①초목 ②식물',
    anatomical: '①해부의 ②해부학의',
    anatomy: '①해부학 ②해부',
    biographer: '전기 작가',
    biology: '생물학',
    broad: '①넓은 ②광',
    controlled: '①제어 ②통제당한',
    credited: '①신용 ②명성',
    detailed: '①세부 ②상세',
    experimentation: '①실험 작업 ②실험법',
    keen: '①예민한 ②예리한',
    luminary: '①발광체 ②선각자',
    organs: '①오르간 ②기관',
    perceived: '①인지하다 ②인식하다',
    refined: '①세련된 ②정제된',
    representations: '①표현 ②표상',
    scholastic: '①학교의 ②학자의',
    skeleton: '골격',
    wondrous: '①놀라운 ②놀랍게',
    adopted: '①채택하다 ②입양하다',
    amalgamations: '①결합 ②아말감법',
    assumed: '①가장한 ②꾸민',
    combat: '①전투 ②싸우다',
    concerns: '①우려 ②관한',
    contemporary: '①현대의 ②동시대의',
    divisions: '①부 ②분단',
    fixtures: '정착물',
    immensely: '①광대하게 ②몹시',
    imported: '①중요하다 ②수입하다',
    jujitsu: '유도 기술',
    modernization: '①현대화 ②근대화',
    muay: '태국의 전통 무술',
    pastime: '①오락 ②취미',
    rattan: '①등 ②그 줄기',
    silat: '무술',
    southeast: '①동남 ②남동',
    applications: '①적용 ②응용',
    attackers: '①공격자 ②공격 선수',
    critical: '①비판적인 ②중요한',
    disclosure: '①폭로 ②발각',
    disrupt: '①방해하다 ②피해를 주다',
    effectiveness: '①효과적인 ②유효성',
    healthcare: '①건강 관리 ②건강 관리의',
    inappropriate: '①부적당한 ②알맞지 않은',
    malicious: '①악성 ②악의 있는',
    mhn: '①남자들 ②사람들',
    misbehave: '①버릇없는 짓을 하다 ②부정을 저지르다',
    network: '①네트워크 ②망',
    phenomena: '현상들',
    preferences: '①선호 ②좋아하기',
    security: '①보안 ②안보',
    servers: '①봉사자 ②서브하는 사람',
    tampered: '①변경하다 ②주무르다',
    untrusted: '옷을 벗은',
    violate: '①위반하다 ②침해하다',
    inefficient: '①비능률적인 ②효과 없는',
    narrative: '①설명적인 ②이야기',
    plot: '①음모 ②줄거리',
    primitive: '①원시의 ②원초적인',
    subtleties: '①희박 ②섬세함',
    vogue: '유행',
    accompanies: '①반주하다 ②동행하다',
    atmospheric: '①대기의 ②대기로 이루어진',
    climatologist: '기후학자',
    cycle: '①주기 ②순환',
    cyclones: '①사이클론 ②선풍',
    cyclonic: '①사이클론의 ②사이클론을 닮은',
    differential: '①미분 ②차등',
    eruption: '①분출 ②발생',
    formation: '①형성 ②대형',
    notable: '①주목할 만한 ②유명한',
    statistical: '①통계의 ②통계상의',
    trigger: '①촉발 ②유발하다',
    volcanic: '①화산의 ②화산 작용에 의한',
    volcanoes: '①화산 ②금시라도 폭발할 듯한 감정',
    advised: '①조언 ②권고',
    beeswax: '①밀랍 ②일',
    commanded: '①명령하다 ②사령부',
    cunning: '①교활한 ②노련한',
    emerged: '①떠오르다 ②드러나다',
    forewarned: '①경고하다 ②경고하다',
    goddess: '여신',
    irresistible: '①저항할 수 없는 ②억누를 수 없는',
    lured: '①마음을 끄는 것 ②미끼',
    mariners: '①선원 ②매리너',
    packed: '꽉 찬',
    peril: '①위험 ②위기',
    perish: '①사라지다 ②죽다',
    predicted: '①예언하다 ②예보하다',
    sailed: '①돛 ②항해',
    undaunted: '①굽히지 않는 ②두려워하지 않는',
    winged: '①날개가 있는 ②빠른',
    access: '접근',
    arbenz: '①열렬한 ②열심인',
    availability: '①유용성 ②유효성',
    backed: '①등가 달린 ②뒷받침이 있는',
    commercial: '①상업용의 ②상업적인',
    compatible: '①호환되는 ②조화하는',
    concentration: '①농축 ②집중',
    concessions: '①양보 ②인정',
    conducted: '①실시하다 ②수행하다',
    conflict: '①갈등 ②분쟁',
    considerable: '①상당한 ②꽤',
    demand: '①요구하다 ②수요',
    derived: '①유래된 ②유도',
    economic: '①경제의 ②경기의',
    ensure: '①ㅇㅇ하기 위해 ②보장하다',
    firms: '회사',
    formation: '①형성 ②대형',
    headquarters: '①본부 ②본사',
    incentives: '①인센티브 ②유인',
    indirect: '간접적인',
    invest: '①투자하다 ②투입하다',
    jacobo: '야코비',
    labour: '노동',
    locating: '①자리잡다 ②정착하다',
    multinational: '①다국적 기업 ②다국적 의',
    operations: '①작용 ②작업 과정',
    policy: '①정책 ②제도',
    political: '①정치의 ②정당의',
    providing: '제공하다',
    quarrels: '①말다툼 ②싸움의 원인',
    resulted: '①결과 ②결의',
    revenue: '①매출 ②수입',
    seek: '①추구하다 ②찾다',
    undermining: '약화시키다',
    basis: '①기초 ②근거',
    behavioral: '①행동의 ②행동에 관한',
    bias: '①편견 ②치우침',
    caregiver: '돌보는 사람',
    characteristic: '①특성 ②독특한',
    consequence: '①결과 ②대가',
    contribute: '①기여하다 ②공헌하다',
    discrimination: '①차별 ②편견',
    eventually: '①결국 ②마침내',
    exhibit: '①전시 ②전시회',
    grasping: '①이해하다 ②잡다',
    increase: '①증가하다 ②늘리다',
    individual: '개인의',
    infant: '①유아의 ②초기의',
    interact: '①작용하다 ②교류하다',
    preference: '①선호 ②좋아하기',
    proximity: '①근접 ②가까움',
    reflexive: '①재귀의 ②반응하는',
    repertoire: '①레퍼토리 ②상연 목록',
    stimuli: 'stimulus의 복수형',
    accuracy: '①정확도 ②정확',
    challenger: '①도전자 ②수하하는 사람',
    explosion: '①폭발 ②급증',
    flashbulb: '플래시 전구',
    humble: '①겸손한 ②초라한',
    iconic: '①상징 ②대표적',
    introductory: '①소개의 ②서두의',
    lack: '①부족 ②ㅇㅇ이 없다',
    mischief: '①장난 ②악영향',
    predict: '①예측하다 ②전망하다',
    questionnaire: '①설문지 ②질문서',
    recall: '①상기하다 ②기억하다',
    specific: '①특정한 ②구체적인',
    vividness: '선명함',
    blunder: '①실수하다 ②머뭇머뭇 걷다',
    bravery: '①용기 ②용감',
    declared: '①선언된 ②선포',
    disqualified: '①자격을 잃은 ②실격이 된',
    employer: '고용주',
    eventually: '①결국 ②마침내',
    exhaustion: '①기진맥진 ②고갈',
    extraordinary: '①특별한 ②뛰어난',
    horrified: '①공포에 휩싸인 ②충격을 받은',
    outset: '①착수 ②시작',
    pastry: '①페이스트리 ②빵과자',
    plight: '①곤경 ②역경',
    spectators: '관중',
    streaked: '①연속 ②계속',
};
const eng = Object.entries(words);

const word = document.querySelector('.word');
const meaning = document.querySelector('.meaning');
const wordNumber = document.querySelector('input#wordNumber');

const create = document.querySelector('.create');

function wordGenerator() {
    for (let i = 0; i < Number(wordNumber.value); i++) {
        let random = Math.floor(Math.random() * eng.length + 1);

        let currentDiv = document.getElementById('wordWrap');

        let newWordSpan = document.createElement('span');
        let newWord = document.createTextNode(`${eng[random][0]}`);
        newWordSpan.appendChild(newWord);
        document.querySelector('#today').insertBefore(newWordSpan, currentDiv);

        let newMeaningSpan = document.createElement('span');
        let newMeaning = document.createTextNode(`${eng[random][1]}`);
        newMeaningSpan.appendChild(newMeaning);
        document.querySelector('#today').insertBefore(newMeaningSpan, currentDiv);
    }

    modalBackground.classList.remove('on');
    modalPopup.classList.remove('on');
    modalPopupOpen.classList.add("hidden")
}
create.addEventListener('click', wordGenerator);

const modalBackground = document.querySelector('#modal');
const modalPopup = document.querySelector('#modal .content');
const modalPopupOpen = document.querySelector('.open');
function modalOpen(event) {
    event.preventDefault();
    modalBackground.classList.add('on');
    modalPopup.classList.add('on');
}
modalPopupOpen.addEventListener('click', modalOpen);
